import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createReadingRun,appendCandidate,appendHumanVersion,requiresReview} from '../src/lib/research-records.ts';
const input=()=>[{itemId:'test-item',documentId:'test-doc',pageId:'p1',revisionId:'r1',uri:'patchouli://texts/test-doc/page-1.md?rev=r1',title:'测试材料',pdfPage:1,fileHash:'test-hash',text:'测试原文'}];
test('a reading round freezes actual input and requires independent reading',()=>{const pages=input(),r=createReadingRun(pages,'释义','我的先行理解');pages[0].text='later OCR';assert.equal(r.input[0].text,'测试原文');assert.throws(()=>createReadingRun(input(),'释义',''),/先阅读/);pages[0].text='x'.repeat(60001);assert.throws(()=>createReadingRun(pages,'释义','理解'),/缩小/);});
test('human revisions preserve raw candidate and explicit ancestry',()=>{const r=createReadingRun(input(),'比较','独立理解'),c={id:'c1',text:'测试机器原文',model:'test-model',state:'complete',created:'2026-10-07',request:[]},r1=appendCandidate(r,c);c.text='changed externally';assert.equal(r1.candidates[0].text,'测试机器原文');const r2=appendHumanVersion(r1,'人工收窄','收窄','只适用于所选段',['c1']),r3=appendHumanVersion(r2,'再次补充','采用','回页核验后补充',['c1']);assert.equal(r3.candidates[0].text,'测试机器原文');assert.equal(r3.versions[1].parentId,r3.versions[0].id);assert.throws(()=>appendCandidate(r3,c),/不能覆盖/);assert.throws(()=>appendHumanVersion(r3,'笔记','采用','',['c1']),/理由/);assert.throws(()=>appendHumanVersion(r3,'笔记','采用','理由',['c2']),/不属于/);});
test('review state follows every input revision and becomes stale again after later edits',()=>{const r=createReadingRun([...input(),{...input()[0],pageId:'p2',revisionId:'r2'}],'比较','先行判断');let revisions={p1:'r1',p2:'r2'};const lib={pageTree:id=>({revision:{tree_revision_id:revisions[id]}})};assert(!requiresReview(lib,r));revisions.p2='r3';assert(requiresReview(lib,r));r.reviews.push({basis:[{pageId:'p1',revisionId:'r1'},{pageId:'p2',revisionId:'r3'}]});assert(!requiresReview(lib,r));revisions.p1='r4';assert(requiresReview(lib,r));});
import {mergeReadingRun} from '../src/lib/research-records.ts';
test('atomic append merges concurrent candidates and refuses changes to frozen input or old results',()=>{const r=createReadingRun(input(),'释义','先读理解'),a=appendCandidate(r,{id:'a',text:'原候选A',request:[]}),b=appendCandidate(r,{id:'b',text:'原候选B',request:[]}),merged=mergeReadingRun(a,b);assert.equal(merged.candidates.length,2);const edited=structuredClone(a);edited.candidates[0].text='覆盖';assert.throws(()=>mergeReadingRun(a,edited),/不能覆盖/);const changed=structuredClone(a);changed.input[0].text='另一版';assert.throws(()=>mergeReadingRun(a,changed),/冻结/);});
