import {Component,h,State,Event,EventEmitter} from '@stencil/core';
import {pdfWorkflow,PdfProgress} from '../../lib/pdf-workflow';
import {validateImportMetadata} from '../../lib/import-metadata';
import {preloadOcr} from '../../lib/ocr';
import {selectItem} from '../../lib/research-context';
@Component({tag:'pdf-import-wizard',styleUrl:'pdf-import-wizard.css',shadow:false})
export class PdfImportWizard {
 @State() files:File[]=[];@State() drafts:{title:string;author:string;publisher:string;date:string}[]=[];@State() busy=false;@State() step=1;@State() error='';@State() message='';@State() results:any[]=[];@State() progress:PdfProgress=pdfWorkflow.state;
 @Event() importClosed:EventEmitter<void>;@Event() importOpenDocument:EventEmitter<string>;
 @Event() importRunningChanged:EventEmitter<boolean>;
 private cancelled=false;private off:()=>void;componentWillLoad(){this.off=pdfWorkflow.subscribe(progress=>this.progress={...progress});}disconnectedCallback(){this.off?.();}
 private choose(files:FileList){this.files=[...files];this.drafts=this.files.map(file=>({title:file.name.replace(/\.pdf$/i,''),author:'',publisher:'',date:''}));this.step=2;this.error='';}
 private edit(index:number,key:string,value:string){this.drafts=this.drafts.map((draft,i)=>i===index?{...draft,[key]:value}:draft);}
 private async start(){this.error='';let metadata;try{metadata=this.drafts.map(draft=>validateImportMetadata({title:draft.title,authors:draft.author.split(/[;；\n]/).filter(name=>name.trim()).map(name=>({role:'author',literal:name.trim()})),fields:{publisher:draft.publisher},issued:draft.date||undefined}));if(!this.files.length)throw Error('请选择 PDF 文件。');}catch(e){this.error=e.message;return;}this.cancelled=false;this.busy=true;this.importRunningChanged.emit(true);this.step=3;this.message='加载 RapidOCR 模型…';try{await preloadOcr();if(this.cancelled)throw new DOMException('已取消','AbortError');this.message='保存题录、关联原件并逐页识别…';this.results=await pdfWorkflow.import(this.files,null,{mode:'ocr',metadata});if(this.results.length)selectItem(this.results.at(-1).item);this.message='已入库：题录、PDF原件、OCR边界框树与检索索引。';this.step=4;}catch(e){this.error=this.cancelled?'':e.message;this.message=this.cancelled||this.progress.phase==='cancelled'?'已取消，已提交页保留。':'可在 OCR 队列继续处理已入库文献。';}finally{this.busy=false;this.importRunningChanged.emit(false);}}
 render(){return <div class="pdf-import-backdrop"><section class="pdf-import-dialog" role="dialog" aria-modal="true" aria-label="导入PDF与编辑题录"><header><h2>导入 PDF</h2><span>{this.step===1?'选择文件':this.step===2?'编辑题录':this.step===3?'RapidOCR 识别':'完成入库'}</span><button title={this.busy?'隐藏进度，任务继续在后台运行':'关闭'} aria-label="关闭PDF导入" onClick={()=>this.importClosed.emit()}>×</button></header><main>{this.step<3&&<label class="import-pick">选择自己的 PDF 文件<input aria-label="选择待导入PDF" type="file" accept=".pdf,application/pdf" multiple onChange={(e:any)=>this.choose(e.target.files)}/></label>}{this.step===2&&this.files.map((file,index)=><fieldset><legend>{file.name}</legend><label>题名<input aria-label={'导入题名'+(index+1)} value={this.drafts[index].title} onInput={(e:any)=>this.edit(index,'title',e.target.value)}/></label><label>作者 <small>多名作者以分号分隔</small><input aria-label={'导入作者'+(index+1)} value={this.drafts[index].author} onInput={(e:any)=>this.edit(index,'author',e.target.value)}/></label><div class="import-optional"><label>出版者<input aria-label={'导入出版者'+(index+1)} value={this.drafts[index].publisher} onInput={(e:any)=>this.edit(index,'publisher',e.target.value)}/></label><label>出版日期<input aria-label={'导入日期'+(index+1)} placeholder="YYYY 或 YYYY-MM-DD" value={this.drafts[index].date} onInput={(e:any)=>this.edit(index,'date',e.target.value)}/></label></div></fieldset>)}{this.step>=3&&<div class="import-progress"><h3>{this.message}</h3>{this.busy&&<progress max={this.progress.total||1} value={this.progress.completed+this.progress.skipped+this.progress.empty}/>}<p role="status" aria-live="polite">{this.progress.detail}</p>{this.busy&&<small>关闭窗口或选择后台运行后，识别继续；点击顶栏“运行中...”可再次查看进度。</small>}{this.progress.total>0&&<p>{this.progress.page} / {this.progress.total} 页 · 新提交 {this.progress.completed} 页</p>}</div>}{this.error&&<p role="alert" class="import-error">{this.error}</p>}</main><footer>{this.busy?<span class="import-background-actions"><button onClick={()=>this.importClosed.emit()}>后台运行</button><button onClick={()=>{this.cancelled=true;pdfWorkflow.cancel();}}>停止识别</button></span>:<button onClick={()=>this.importClosed.emit()}>{this.step===4?'完成':'取消'}</button>}{this.step===2&&<button onClick={()=>void this.start()}>保存题录并导入、识别</button>}{this.step===4&&<button onClick={()=>{this.files=[];this.drafts=[];this.results=[];this.error='';this.message='';this.step=1;}}>再导入 PDF</button>}{this.step===4&&this.results.length>0&&<button onClick={()=>this.importOpenDocument.emit(this.results.at(-1).document)}>在 PDF 工作台查看</button>}</footer></section></div>;}
}
