import {Component,h,Prop,State} from '@stencil/core';
import {PatchouliRequest} from '../../lib/patchouli-pages';
@Component({tag:'standalone-lab',styleUrl:'standalone-lab.css',shadow:false})
export class StandaloneLab {
 @Prop() pageId='D16';@Prop() active=false;@State() example=0;@State() indexMode='identity';
 @State() reader:PatchouliRequest;
 private open=(event:CustomEvent)=>{if(!this.active)return;try{const url=new URL(event.detail),match=url.pathname.match(/^\/([^/]+)\/page-(\d+)\.md$/);if(url.protocol==='patchouli:'&&url.hostname==='texts'&&match)this.reader={page:'reader',documentId:match[1],pageNumber:Number(match[2]),revisionId:url.searchParams.get('rev')||'',evidenceUri:event.detail};}catch{}};
 componentWillLoad(){window.addEventListener('workbench-open-document',this.open);}
 disconnectedCallback(){window.removeEventListener('workbench-open-document',this.open);}
 private examples=[{title:'从论文进入研究',kind:'书目与原文',text:'已有题录、原件与原文地址构成稳定入口。',record:'题名 · 责任者 · 出版日期 · 版本'}, {title:'新问题带来新记录',kind:'追加来源笔记',text:'提出新的问题时，增加相应笔记，不把旧字段改成另一种含义。',record:'原话 · 释义 · 推断 · 证据地址'}, {title:'新的比较视角',kind:'追加关系与索引',text:'围绕人物、事件或概念建立新入口；旧材料仍然可以回查。',record:'关系类型 · 明确理由 · 问题索引'}];
 private body(){if(!this.active)return <div class="workbench-sleep"/>;if(this.pageId==='D10')return <section class="standalone-experiment"><div class="lab-toolbar"><h3>对象身份与可重建索引</h3><button aria-pressed={String(this.indexMode==='identity')} onClick={()=>this.indexMode='identity'}>同一文献是谁</button><button aria-pressed={String(this.indexMode==='objects')} onClick={()=>this.indexMode='objects'}>四种对象视角</button><button aria-pressed={String(this.indexMode==='tables')} onClick={()=>this.indexMode='tables'}>真实索引重建</button></div><div hidden={this.indexMode!=='identity'}><document-identity/></div><div hidden={this.indexMode!=='objects'} class="object-perspectives">{[['Zotero','条目＋附件','条目身份与附件关联'],['JabRef','BibTeX记录','引用键与字段'],['Tropy','照片＋项目','图像材料与项目元数据'],['Patchouli','题录／文档实例／文件资产','实体ID、文件哈希与修订']].map(([tool,object,key])=><article><h3>{tool}</h3><strong>{object}</strong><p>{key}</p></article>)}<p>材料及其身份是长期依据；检索索引是从正文建立的可重建视图。</p></div><div hidden={this.indexMode!=='tables'}><projection-lab/></div></section>;if(this.pageId==='D18')return <reading-agent/>;if(this.pageId==='D27')return <section class="standalone-experiment"><h3>交换、备份与独立恢复实验</h3><backup-lab/></section>;
 const example=this.examples[this.example];return <section class="structure-example" aria-label="可演化结构示例"><div><h3>稳定的材料，能够生长的研究入口</h3><p>选择一个研究阶段，观察记录怎样追加。</p><nav>{this.examples.map((e,i)=><button aria-pressed={String(i===this.example)} class={i===this.example?'selected':''} onClick={()=>this.example=i}>{e.title}</button>)}</nav><article key={this.example}><small>{example.kind}</small><h2>{example.title}</h2><p>{example.text}</p><code>{example.record}</code></article></div><div class="structure-stack"><div class={'structure-block extension '+(this.example>=2?'present':'')}><strong>关系与问题索引</strong><small>因比较任务而追加</small></div><div class={'structure-block extension '+(this.example>=1?'present':'')}><strong>来源笔记</strong><small>因阅读问题而追加</small></div><div class="structure-block core present"><strong>文献身份与原文</strong><small>题录 · 原件 · 可回查地址</small></div></div></section>;
 }
 render(){return <div class="standalone-frame"><div class="standalone-body" hidden={!!this.reader}>{this.body()}</div>{this.reader&&<patchouli-app active={this.active} initialPage="reader" request={this.reader} externalReturn={true} returnLabel="返回教学实验" onPatchouliReturn={()=>this.reader=null}/>}</div>;}
}
