import {Component,Element,h,Listen,Prop,State} from '@stencil/core';
import {liveLibrary} from '../../lib/live-library';
import {selectedItem,selectItem} from '../../lib/research-context';
import {activeRun,appendHumanVersion,createReadingRun,currentBasis,readRuns,requiresReview,saveRun,setActiveRun,snapshotPages,ReadingInput,ReadingRun} from '../../lib/research-records';
import {downloadBytes} from '../shared/download';

@Component({tag:'research-ledger',styleUrl:'research-ledger.css',shadow:false})
export class ResearchLedger {
  @Element() el:HTMLElement;@Prop() pageId='D18';
  @State() runs:ReadingRun[]=[];@State() run:ReadingRun;
  @State() itemId='';@State() documentId='';@State() first=1;@State() last=1;
  @State() proposed:ReadingInput[]=[];@State() task='释义';@State() independent='';@State() human='';@State() decision='待查';@State() reason='';
  @State() candidates:string[]=[];@State() message='';@State() busy=false;@State() query='';@State() tick=0;
  private off:()=>void;
  componentWillLoad(){this.off=liveLibrary.subscribe(state=>{if(state==='ready')this.refresh();});}
  disconnectedCallback(){this.off?.();}
  @Listen('course-reading-change',{target:'window'}) changed(){this.refresh();}
  @Listen('research-selection',{target:'window'}) selected(){const id=selectedItem();if(id!==this.itemId){this.itemId=id;this.documentId='';this.first=1;this.last=1;this.independent='';}}
  private get lib(){return liveLibrary.getLibrary();}
  private draftKey(){return 'course-reading-draft/'+this.lib?.libraryId+'/'+(this.run?.id||'new')+'/'+this.pageId;}
  private draft(){localStorage.setItem(this.draftKey(),JSON.stringify({human:this.human,decision:this.decision,reason:this.reason,candidates:this.candidates,independent:this.independent}));}
  private refresh(){if(!this.lib)return;this.runs=readRuns(this.lib);const run=activeRun(this.lib),changed=run?.id!==this.run?.id;this.run=run;this.itemId ||= selectedItem()||this.lib.items()[0]?.item_id||'';this.tick++;
    if(changed){let draft:any={};try{draft=JSON.parse(localStorage.getItem(this.draftKey())||'{}');}catch{}const last=run?.versions.at(-1);this.human=draft.human??last?.text??'';this.decision=draft.decision??last?.decision??'待查';this.reason=draft.reason??'';this.candidates=draft.candidates??[];this.independent=draft.independent??'';}
  }
  private async perform(action:()=>Promise<any>){if(this.busy)return;this.busy=true;try{await action();this.message='已写入本机书库的课程扩展记录；原始候选与旧版本保留。';this.refresh();}catch(e){this.message=e.message;}finally{this.busy=false;}}
  private async begin(){await this.perform(async()=>{const docs=this.documents(),doc=this.documentId||docs[0]?.document_instance_id;const run=createReadingRun(this.proposed.length?this.proposed:snapshotPages(this.lib,doc,this.first,this.last),this.task,this.independent);await saveRun(this.lib,run);this.human='';this.reason='';this.candidates=[];this.proposed=[];this.draft();});}
  private preview(){try{const doc=this.documentId||this.documents()[0]?.document_instance_id,pages=snapshotPages(this.lib,doc,this.first,this.last);const next=[...this.proposed,...pages.filter(p=>!this.proposed.some(old=>old.uri===p.uri))];if(next.reduce((n,p)=>n+p.text.length,0)>60000)throw Error('合并输入超过6万字符，请缩小范围');this.proposed=next;this.message='已加入待冻结范围，请预览实际文字后确定。';}catch(e){this.message=e.message;}}
  private documents(){return this.lib?.rows('select * from document_instances where item_id=? and status=\'active\' order by is_primary desc,created_at',[this.itemId])||[];}
  private chooseRun(id:string){setActiveRun(this.lib,id);const run=this.runs.find(r=>r.id===id);if(run)selectItem(run.itemId);}
  private async takeMarkdown(){const editor=this.el.closest('deck-slide')?.querySelector('markdown-lab') as HTMLMarkdownLabElement;if(!editor){this.message='请在下方直接填写人工修订。';return;}this.human=await editor.getText();this.draft();this.message='已复制本页 Markdown 草稿，确认来源和理由后另存人工版本。';}
  private async saveHuman(){await this.perform(async()=>saveRun(this.lib,appendHumanVersion(this.run,this.human,this.decision,this.reason,this.candidates)));}
  private async review(){await this.perform(async()=>{if(!this.reason.trim())throw Error('请回读新依据，写出复核理由');const run=JSON.parse(JSON.stringify(this.run));run.reviews.push({id:crypto.randomUUID(),created:new Date().toISOString(),decision:this.decision,reason:this.reason.trim(),basis:currentBasis(this.lib,run)});await saveRun(this.lib,run);});}
  render(){if(!this.lib)return <p>课程阅读记录等待书库启动。</p>;const docs=this.documents(),run=this.run,items=this.lib.items().filter(i=>(i.title+' '+i.note).toLowerCase().includes(this.query.toLowerCase()));return <section class="reading-ledger" aria-label="课程阅读记录">
    <header><div><h2>把这次阅读接入下一次研究</h2><p>助教工作台保存材料与正文；这里保存本轮阅读判断，作为课程扩展写入同一 SQLite。输入与候选分别保留。</p></div><div class="ledger-controls"><button onClick={()=>(this.el.closest('deck-slide')?.querySelector('.slide-scroll') as HTMLElement)?.scrollTo({top:0,behavior:'smooth'})}>返回本页工作台 ↑</button><button onClick={()=>downloadBytes(new TextEncoder().encode(JSON.stringify({schema:'pku-reading-records/v1',libraryId:this.lib.libraryId,runs:this.runs},null,2)),'reading-records.json')}>下载阅读记录</button></div></header>
    <div class="ledger-start"><h3>1　先读原页，再确定本轮输入</h3><div class="ledger-controls">
      <input aria-label="搜索本轮材料" placeholder="搜索题名或备注" value={this.query} onInput={(e:any)=>this.query=e.target.value}/>
      <select aria-label="本轮题录" onChange={(e:any)=>{this.itemId=e.target.value;this.documentId='';this.first=this.last=1;selectItem(this.itemId);}}>{items.map(i=><option value={i.item_id} selected={i.item_id===this.itemId}>{i.title}</option>)}</select>
      <select aria-label="本轮文档实例" onChange={(e:any)=>{this.documentId=e.target.value;this.first=this.last=1;}}>{docs.map(d=><option value={d.document_instance_id} selected={d.document_instance_id===(this.documentId||docs[0]?.document_instance_id)}>{d.title}</option>)}</select>
      <label>PDF 页 <input aria-label="输入起始页" type="number" min="1" value={this.first} onInput={(e:any)=>this.first=Number(e.target.value)}/>—<input aria-label="输入结束页" type="number" min={this.first} value={this.last} onInput={(e:any)=>this.last=Number(e.target.value)}/></label>
      <select aria-label="本轮阅读任务" title="筛选安排优先级；抽取取原话；释义解释语境；概括限定范围；比较并列异同；验证检查依据" onChange={(e:any)=>this.task=e.target.value}>{['筛选','抽取','释义','概括','比较','验证'].map(t=><option value={t} selected={t===this.task}>{t}</option>)}</select>
      <button disabled={!docs.length} onClick={()=>window.dispatchEvent(new CustomEvent('workbench-open-document',{detail:{uri:'patchouli://texts/'+(this.documentId||docs[0]?.document_instance_id)+'/page-'+this.first+'.md'}}))}>先看所选原页</button>
      <button onClick={()=>this.preview()}>预览并加入所选页段（可跨文献）</button>
    </div>{this.proposed.length>0&&<details open><summary>待冻结范围：{this.proposed.length}页，{new Set(this.proposed.map(p=>p.documentId)).size}份文档 <button onClick={()=>this.proposed=[]}>清空待选范围</button></summary>{this.proposed.map(p=><details><summary>{p.title} · PDF {p.pdfPage}<button onClick={()=>this.proposed=this.proposed.filter(old=>old.uri!==p.uri)}>移除此页</button></summary><pre>{p.text}</pre></details>)}</details>}<textarea aria-label="模型前的独立阅读" placeholder="先看原页：我理解作者在说什么？依据在哪里？尚有什么疑问？保存后再比较机器。" value={this.independent} onInput={(e:any)=>{this.independent=e.target.value;this.draft();}}/><button disabled={this.busy} onClick={()=>void this.begin()}>保存独立阅读并冻结输入，开始新一轮</button></div>
    <div class="ledger-controls"><label>恢复此前轮次 <select aria-label="选择阅读轮次" onChange={(e:any)=>this.chooseRun(e.target.value)}><option value="">尚未确定本轮</option>{this.runs.map(r=><option value={r.id} selected={r.id===run?.id}>{r.created.slice(5,16)} · {r.task} · {r.input[0]?.title}</option>)}</select></label>{run&&<strong class={requiresReview(this.lib,run)?'review-needed':''}>{requiresReview(this.lib,run)?'依据已变化，请回读后复核':'所记录依据未变化'}</strong>}</div>
    {run&&<div class="ledger-grid"><article><h3>2　本轮已保存的人工先行理解</h3><p class="ledger-text">{run.independent}</p><details><summary>实际输入：{run.input.length}页 · {run.input.reduce((n,p)=>n+p.text.length,0)}字符</summary>{run.input.map(p=><section><a href="#" onClick={e=>{e.preventDefault();window.dispatchEvent(new CustomEvent('workbench-open-document',{detail:{uri:p.uri}}));}}>{p.title} · PDF {p.pdfPage} · {p.revisionId.slice(0,8)}</a><pre>{p.text}</pre></section>)}</details><h3>3　模型原始候选（不可覆盖）</h3>{run.candidates.length?run.candidates.map((c,index)=><details open={index===run.candidates.length-1}><summary>候选 {index+1} · {c.model} · {c.state} · {c.created.slice(11,19)}</summary><label><input type="checkbox" checked={this.candidates.includes(c.id)} onChange={(e:any)=>{this.candidates=e.target.checked?[...this.candidates,c.id]:this.candidates.filter(id=>id!==c.id);this.draft();}}/>作为人工版本的来源</label><div class="ledger-text">{c.text}</div><button onClick={()=>{this.human=c.text;this.candidates=[c.id];this.draft();this.message="已复制为人工草稿；原候选保留，请回原页修改并写理由后另存。";}}>以此候选起草人工修订</button><details><summary>实际请求和工具返回</summary><pre>{JSON.stringify(c.request,null,2)}</pre></details></details>):<p>暂无模型候选。可在 D18 发送本轮输入；也可只完成人工阅读。</p>}</article>
    <article><h3>4　人工修订与采用理由</h3>{['D19','D20','D23'].includes(this.pageId)&&<button onClick={()=>void this.takeMarkdown()}>把本页 Markdown 草稿复制到人工修订</button>}<textarea aria-label="人工阅读修订" placeholder="结合原页与候选，写自己的解释；区分原话、释义和推断。" value={this.human} onInput={(e:any)=>{this.human=e.target.value;this.draft();}}/><div class="ledger-controls"><select aria-label="采用决定" title="采用：核验后在所定范围使用；收窄：减小范围或强度；待查：保留问题并补证" onChange={(e:any)=>{this.decision=e.target.value;this.draft();}}>{['采用','收窄','待查'].map(d=><option value={d} selected={d===this.decision}>{d}</option>)}</select><button disabled={this.busy} onClick={()=>void this.saveHuman()}>另存人工版本，保留来源</button></div><textarea aria-label="判断或复核理由" placeholder="原页哪一处支持或限制这个解释？下一步回读／补证什么？依据变化后在此写复核理由。" value={this.reason} onInput={(e:any)=>{this.reason=e.target.value;this.draft();}}/>{run.versions.map((v,i)=><details><summary>人工版本 {i+1} · {v.decision} · {v.candidateIds.length}项候选来源</summary><p class="ledger-text">{v.text}</p><p>理由：{v.reason}</p><small>版本 {v.id.slice(0,8)}{v.parentId?' ← '+v.parentId.slice(0,8):''}</small></details>)}<h3>5　依据改变后回读并追加复核</h3><button disabled={this.busy} onClick={()=>void this.review()}>保存本次复核与当前依据</button>{run.reviews.map(r=><p>{r.created.slice(0,19)} · {r.decision}：{r.reason}</p>)}</article></div>}
    <p role="status">{this.message||'人工文本草稿在本机暂存；点击保存才写入书库扩展记录。完整 ZIP 同时备份数据库、原件及阅读记录。'}</p>
  </section>;}
}
