import type { BoxCandidate } from './library';
export type TreeBox = BoxCandidate & {id:string;type:string;parent:string|null};
export const BOX_TYPES:Record<string,string>={logical_page:'逻辑页',text:'正文',title:'标题',ref_text:'参考文献',equation:'公式',list:'列表',image:'图像',table:'表格',chart:'图表',code:'代码',algorithm:'算法',image_caption:'图注',image_footnote:'图像脚注',table_caption:'表注',table_footnote:'表格脚注',chart_caption:'图表说明',chart_footnote:'图表脚注',code_caption:'代码说明',code_footnote:'代码脚注',header:'页眉',footer:'页脚',page_number:'页码',page_aside_text:'旁注',page_footnote:'脚注'};
export const cloneBoxes=(boxes:TreeBox[]):TreeBox[]=>boxes.map(box=>({...box}));
export function descendants(boxes:TreeBox[],id:string):Set<string>{const result=new Set<string>();const visit=(parent:string)=>{for(const box of boxes.filter(box=>box.parent===parent)){if(result.has(box.id))throw Error('边界框树存在循环');result.add(box.id);visit(box.id);}};visit(id);return result;}
export function preorder(boxes:TreeBox[]):{box:TreeBox;depth:number}[]{const result:{box:TreeBox;depth:number}[]=[],seen=new Set<string>();const visit=(parent:string|null,depth:number)=>{for(const box of boxes.filter(box=>box.parent===parent)){if(seen.has(box.id))throw Error('边界框树存在循环');seen.add(box.id);result.push({box,depth});visit(box.id,depth+1);}};visit(null,0);if(result.length!==boxes.length)throw Error('边界框树存在断开的节点');return result;}
export function validateBoxTree(boxes:TreeBox[]){
 if(new Set(boxes.map(box=>box.id)).size!==boxes.length)throw Error('边界框ID重复');
 for(const box of boxes){if(![box.x,box.y,box.width,box.height].every(Number.isFinite)||box.x<0||box.y<0||box.width<=0||box.height<=0||box.x+box.width>1.000001||box.y+box.height>1.000001)throw Error('边界框必须位于页面内，且宽高大于0');if(box.parent&&boxes.find(parent=>parent.id===box.parent)?.type!=='logical_page')throw Error('只有逻辑页能包含子框');if(box.type==='logical_page'&&box.suppressed)throw Error('逻辑页不能抑制');if(box.type!=='logical_page'&&boxes.some(child=>child.parent===box.id))throw Error('正文框不能包含子框');if(box.payloadJson)JSON.parse(box.payloadJson);}
 preorder(boxes);
}
export function moveBox(boxes:TreeBox[],id:string,parent:string|null,before:string|null=null):TreeBox[]{
 const original=boxes.find(box=>box.id===id);if(!original)throw Error('未选择边界框');const branch=descendants(boxes,id);branch.add(id);
 if(parent&&branch.has(parent))throw Error('不能把边界框放入自己的子树');if(parent&&boxes.find(box=>box.id===parent)?.type!=='logical_page')throw Error('父节点必须为逻辑页');
 const moving=boxes.filter(box=>branch.has(box.id)).map(box=>({...box,...(box.id===id?{parent}:{})})),rest=boxes.filter(box=>!branch.has(box.id));
 let index=rest.length;if(before){const target=rest.find(box=>box.id===before);if(!target||target.parent!==parent)throw Error('目标必须是同一父节点的兄弟框');index=rest.findIndex(box=>box.id===before);}else if(parent){const children=descendants(rest,parent);index=Math.max(rest.findIndex(box=>box.id===parent),...rest.map((box,index)=>children.has(box.id)?index:-1))+1;}
 return [...rest.slice(0,index),...moving,...rest.slice(index)];
}
export function shiftBox(boxes:TreeBox[],id:string,step:number){const box=boxes.find(box=>box.id===id),siblings=boxes.filter(item=>item.parent===box?.parent),index=siblings.findIndex(item=>item.id===id),target=index+step;if(!box||target<0||target>=siblings.length)return boxes;return moveBox(boxes,id,box.parent,step<0?siblings[target].id:siblings[target+1]?.id||null);}
export function indentBox(boxes:TreeBox[],id:string){const box=boxes.find(box=>box.id===id),siblings=boxes.filter(item=>item.parent===box?.parent),previous=siblings[siblings.findIndex(item=>item.id===id)-1];if(previous?.type!=='logical_page')throw Error('缩进需要前一个兄弟框是逻辑页');return moveBox(boxes,id,previous.id);}
export function outdentBox(boxes:TreeBox[],id:string){const box=boxes.find(box=>box.id===id),parent=boxes.find(item=>item.id===box?.parent);if(!box||!parent)throw Error('当前框已在根层');const siblings=boxes.filter(item=>item.parent===parent.parent),index=siblings.findIndex(item=>item.id===parent.id);return moveBox(boxes,id,parent.parent,siblings[index+1]?.id||null);}
export function removeBoxes(boxes:TreeBox[],ids:string[]){const removed=new Set(ids);for(const id of ids)for(const child of descendants(boxes,id))removed.add(child);if(boxes.some(box=>!removed.has(box.id)&&removed.has(box.continuesFromBoxId)))throw Error('有续接框引用这些节点，请先处理续接关系');return boxes.filter(box=>!removed.has(box.id));}
export function textOf(box:TreeBox){const payload=JSON.parse(box.payloadJson||'{}');return String(payload.markdown??payload.latex??payload.code??payload.description??box.text??'');}
export function setBoxText(box:TreeBox,text:string):TreeBox{const payload=JSON.parse(box.payloadJson||'{}'),key=box.type==='equation'?'latex':['code','algorithm'].includes(box.type)?'code':['image','chart'].includes(box.type)?'description':'markdown';payload[key]=text;return {...box,text,payloadJson:JSON.stringify(payload)};}
export function createBox(type='text',parent:string|null=null,geometry={x:.1,y:.1,width:.8,height:.1}):TreeBox{return {id:crypto.randomUUID(),parent,type,...geometry,payloadJson:type==='logical_page'?undefined:JSON.stringify({markdown:''}),text:'',suppressed:false,headingLevel:type==='title'?1:null};}
export function splitBox(boxes:TreeBox[],id:string,offset:number){const box=boxes.find(box=>box.id===id);if(!box||['logical_page','image','chart','table'].includes(box.type))throw Error('请选择可拆分的文字框');const text=textOf(box);if(offset<=0||offset>=text.length)throw Error('拆分位置应在文字中间');const first=setBoxText({...box,height:box.height/2},text.slice(0,offset)),second=setBoxText({...box,id:crypto.randomUUID(),y:box.y+box.height/2,height:box.height/2},text.slice(offset));const index=boxes.findIndex(box=>box.id===id);return [...boxes.slice(0,index),first,second,...boxes.slice(index+1)];}
export function mergeBoxes(boxes:TreeBox[],ids:string[]){const selected=boxes.filter(box=>ids.includes(box.id));if(selected.length<2||selected.some(box=>box.parent!==selected[0].parent||['logical_page','image','chart','table'].includes(box.type)))throw Error('合并需要同一父节点下的多个文字框');const left=Math.min(...selected.map(box=>box.x)),top=Math.min(...selected.map(box=>box.y)),right=Math.max(...selected.map(box=>box.x+box.width)),bottom=Math.max(...selected.map(box=>box.y+box.height));const merged=setBoxText({...selected[0],type:'text',x:left,y:top,width:right-left,height:bottom-top,headingLevel:null},selected.map(textOf).join('\n\n'));const rest=removeBoxes(boxes,selected.slice(1).map(box=>box.id));return rest.map(box=>box.id===merged.id?merged:box);}
interface EditDraft { boxes:TreeBox[];baseline:string;selected:string[];undo:TreeBox[][];redo:TreeBox[][]; }
const drafts=new WeakMap<object,Map<string,EditDraft>>();
export function boxDrafts(database:object){let value=drafts.get(database);if(!value){value=new Map();drafts.set(database,value);}return value;}
