import type {Library} from './library';
import {buildFtsQuery} from './search-text';
type Clause={key:string;value:string};
export const PROGRESSIVE_TOOLS=[
 {type:'function',function:{name:'find',description:'Browse or search the Patchouli VFS progressively. Start with find({}) to discover roots. Omit query to browse; browse items to identify a work, then its text directory to see pages. Search a chosen scope using short terms; root is discovery-only. Use returned cursor for pagination.',parameters:{type:'object',properties:{in:{type:'string',description:'Scope URI, e.g. patchouli://items/ or patchouli://texts/{document-id}/'},query:{type:'string',description:'Short search terms. Omit to browse.'},where:{type:'array',items:{type:'string'},description:'Filters KEY=VALUE: item_id, item_type, item_status, tag, collection_id, citable.'},literal:{type:'boolean'},limit:{type:'integer',minimum:1,maximum:50},cursor:{type:'string'},detail:{type:'string',enum:['short','long']}},additionalProperties:false}}},
 {type:'function',function:{name:'fetch',description:'Read VFS resources. Fetch library.toon for library context, an item .bib for metadata and attachment links, a text directory for a page outline, then specific pages or revision/box evidence. range supports lines:S-E or pages:S-E. Respect complete/truncated and next_range; continue rather than assuming an excerpt is the full work.',parameters:{type:'object',properties:{uris:{type:'array',items:{type:'string'},minItems:1,maxItems:10},range:{type:'string'},limit_bytes:{type:'integer',minimum:512,maximum:65536}},required:['uris'],additionalProperties:false}}},
 {type:'function',function:{name:'cite',description:'Render actual bibliography in MLA, APA, Chicago or 世界历史 for item, document, page or evidence URIs. Also returns the exact evidence references. Obtain source details through find/fetch before drawing conclusions.',parameters:{type:'object',properties:{refs:{type:'array',items:{type:'string'}},style:{type:'string',description:'patchouli://csl-styles/{mla|apa|chicago|world-history}.csl'},locale:{type:'string'},bibliography:{type:'boolean'}},required:['refs'],additionalProperties:false}}},
];
const styleList=[['mla','MLA 第9版'],['apa','APA 第7版'],['chicago','Chicago 第18版'],['world-history','《世界历史》']];
const itemUri=(id:string)=>'patchouli://items/'+id+'.bib',docUri=(id:string)=>'patchouli://texts/'+id+'/',pageUri=(id:string,page:number,rev?:string,box?:string)=>'patchouli://texts/'+id+'/page-'+page+'.md'+(rev?'?rev='+rev+(box?'&box='+box:''):'');
const encode=(value:any)=>btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(value))));
const decode=(value:string)=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(value),c=>c.charCodeAt(0))));
export function createProgressiveTools(lib:Library,renderCitation?:(records:any[],style:string,locale:string)=>Promise<string>){
 const revision=()=> 'lib:'+lib.rows('select library_revision from library_metadata')[0]?.library_revision;
 const item=(id:string)=>lib.items().find(item=>item.item_id===id);
 const documents=()=>lib.rows('select d.*,i.title item_title,i.item_type,i.status item_status from document_instances d join items i on i.item_id=d.item_id where i.deleted_at is null and i.merged_into_item_id is null');
 const clauses=(where:any):Clause[]=>(where||[]).map(clause=>{if(typeof clause==='string'){const equal=clause.indexOf('=');if(equal<1)throw Error('where requires KEY=VALUE');return {key:clause.slice(0,equal),value:clause.slice(equal+1)};}return clause;});
 const permitted=new Set(['item_id','item_type','item_status','tag','collection_id','citable']);
 const accepts=(record:any,where:Clause[])=>where.every(({key,value})=>{if(!permitted.has(key))throw Error('Unsupported filter '+key);const i=item(record.item_id);if(key==='tag')return JSON.parse(i?.tags_json||'[]').includes(value);if(key==='collection_id')return !!lib.rows('select item_id from item_collections where collection_id=? and item_id=?',[value,record.item_id]).length;if(key==='citable')return value===(i?'true':'false');return String(key==='item_status'?i?.status:key==='item_type'?i?.item_type:record.item_id)===value;});
 const envelope=(operation:string,entries:any[],meta:any={})=>({operation,meta:{library_revision:revision(),...meta},entries});
 function find(args:any={}){let scope=args.in||'patchouli://',query=args.query?.trim()||'',where=clauses(args.where),offset=0;const limit=Math.max(1,Math.min(50,Number(args.limit)||20));if(args.cursor){const cursor=decode(args.cursor);if(cursor.revision!==revision())throw Error('CURSOR_EXPIRED: browse the scope again');if(args.in&&scope!==cursor.scope)throw Error('CURSOR_SCOPE_MISMATCH');scope=cursor.scope;query=cursor.query;where=cursor.where;offset=cursor.offset;}
  const url=new URL(scope);if(url.protocol!=='patchouli:')throw Error('Use patchouli:// VFS scopes');let all:any[]=[];
  if(!url.hostname){if(query||where.length)throw Error('Root is discovery-only: find({}), then select a returned directory');all=[{uri:'patchouli://items/',title:'/items',type:'directory'},{uri:'patchouli://texts/',title:'/texts',type:'directory'},{uri:'patchouli://csl-styles/',title:'/csl-styles',type:'directory'},{uri:'patchouli://library.toon',title:'当前书库信息',type:'file'}];}
  else if(url.hostname==='items'){const fileId=url.pathname.match(/^\/([^/]+)\.bib$/)?.[1];all=lib.items().filter(i=>(!fileId||i.item_id===fileId)&&accepts(i,where));if(query){const terms=query.toLowerCase().split(/\s+/).filter(Boolean);all=all.filter(i=>{const value=[i.title,i.publisher,i.publication_title,i.creators_json].join(' ').toLowerCase();return args.literal?value.includes(query.toLowerCase()):terms.every(term=>value.includes(term));});}all=all.map(i=>({uri:itemUri(i.item_id),title:i.title,type:'bibliography',item_id:i.item_id,...(args.detail==='long'?{item_type:i.item_type,authors:i.creators_json,year:i.date,documents:documents().filter(d=>d.item_id===i.item_id).map(d=>docUri(d.document_instance_id))}:{})}));}
  else if(url.hostname==='texts'){const match=url.pathname.match(/^\/([^/]+)\/(?:page-(\d+)\.md)?$/),documentId=match?.[1],pageNumber=match?.[2]?Number(match[2]):null;const docs=documents().filter(doc=>(!documentId||doc.document_instance_id===documentId)&&accepts(doc,where));if(documentId&&!docs.length)throw Error('Document not found in the selected scope');
   if(!query){if(!documentId)all=docs.map(d=>({uri:docUri(d.document_instance_id),title:d.item_title,type:'text_document',item_uri:itemUri(d.item_id),page_count:lib.pages(d.document_instance_id).length}));else all=lib.rows('select p.*,r.tree_revision_id from pages p left join document_tree_revisions r on r.page_id=p.page_id and r.is_current=1 and r.status=\'committed\' where p.document_instance_id=? order by p.page_index',[documentId]).filter(p=>!pageNumber||p.page_index+1===pageNumber).map(p=>({uri:pageUri(documentId,p.page_index+1,p.tree_revision_id),title:'第'+(p.page_index+1)+'页',type:'text_page',available:!!p.tree_revision_id}));}
   else{const ids=docs.map(d=>d.document_instance_id);if(ids.length){const params:any[]=[...ids],condition=args.literal?'instr(lower(s.resolved_text),lower(?))>0':'s.unit_id in(select unit_id from search_units_fts where search_units_fts match ?)';params.push(args.literal?query:buildFtsQuery(query));let pageFilter='';if(pageNumber){pageFilter=' and p.page_index=?';params.push(pageNumber-1);}all=lib.rows('select s.*,p.page_index,i.title from search_units s join pages p on p.page_id=s.page_id join document_tree_revisions r on r.tree_revision_id=s.tree_revision_id join document_instances d on d.document_instance_id=s.document_instance_id join items i on i.item_id=d.item_id where s.document_instance_id in('+ids.map(()=>'?').join(',')+') and s.status=\'current\' and r.is_current=1 and r.status=\'committed\' and '+condition+pageFilter+' order by d.document_instance_id,p.page_index,s.ordinal',params).map(row=>({uri:pageUri(row.document_instance_id,row.page_index+1,row.tree_revision_id,row.box_id),title:row.title,type:'evidence',page:row.page_index+1,excerpt:row.resolved_text.slice(0,args.detail==='long'?1400:350)}));}}
  }else if(url.hostname==='csl-styles')all=styleList.map(([id,title])=>({uri:'patchouli://csl-styles/'+id+'.csl',title,type:'csl_style'}));else throw Error('Scope unavailable in this reading workspace');
  const entries=all.slice(offset,offset+limit),cursor=offset+limit<all.length?encode({revision:revision(),scope,query,where,offset:offset+limit}):null;return {...envelope('find',entries,{domain_total:all.length,filtered_total:all.length,shown_total:entries.length}),continuation:cursor,...(!entries.length&&query?{message:'No matches in this scope. Browse it without query, identify the work, then search its text directory with fewer terms.'}:{})};
 }
 async function fetchResources(args:any){const entries=[];for(const uri of args.uris||[]){const url=new URL(uri);if(url.protocol!=='patchouli:')throw Error('Unsupported URI');let content='',resourceType='',parent='',nextRange:string=null;
   if(url.hostname==='library.toon'){resourceType='library';content=JSON.stringify({library_revision:revision(),items:lib.items().length,documents:documents().length,roots:['patchouli://items/','patchouli://texts/','patchouli://csl-styles/'],collections:lib.collections(),tools:['find','fetch','cite']},null,2);}
   else if(url.hostname==='items'){const id=url.pathname.match(/^\/([^/]+)\.bib$/)?.[1],record=item(id);if(!record)throw Error('Item not found');resourceType='bibliography';parent=itemUri(id);const csl=lib.csl().find(c=>c.id===id),escape=(text:any)=>String(text||'').replaceAll('\\','\\textbackslash{}').replaceAll('{','\\{').replaceAll('}','\\}');content='@'+(record.item_type==='book'?'book':'misc')+'{'+id+',\n'+[['title',record.title],['author',(csl?.author||[]).map(c=>c.literal||[c.family,c.given].filter(Boolean).join(', ')).join(' and ')],['date',record.date||csl?.issued?.['date-parts']?.[0]?.join('-')],['publisher',record.publisher],['location',record.place]].filter(([,v])=>v).map(([k,v])=>'  '+k+' = {'+escape(v)+'}').join(',\n')+'\n}\n\n'+documents().filter(d=>d.item_id===id).map(d=>'全文入口：'+docUri(d.document_instance_id)).join('\n');}
   else if(url.hostname==='texts'){const docMatch=url.pathname.match(/^\/([^/]+)\/$/);if(docMatch){const id=docMatch[1],doc=documents().find(d=>d.document_instance_id===id);if(!doc)throw Error('Document not found');parent=itemUri(doc.item_id);resourceType='text_document';const pages=lib.pages(id),range=args.range?.match(/^pages:(\d+)-(\d+)$/);if(range){const selected=pages.slice(Number(range[1])-1,Number(range[2]));content=selected.map(page=>'## 第'+(page.page_index+1)+'页\n'+lib.fetch(pageUri(id,page.page_index+1)).text).join('\n\n');}else content='# '+doc.item_title+'\n\n'+pages.map(page=>{const tree=lib.pageTree(page.page_id);return '第'+(page.page_index+1)+'页 · '+pageUri(id,page.page_index+1,tree.revision?.tree_revision_id);}).join('\n');}
    else{const match=url.pathname.match(/^\/([^/]+)\/page-(\d+)\.md$/);if(!match)throw Error('Unknown text URI');const doc=documents().find(d=>d.document_instance_id===match[1]);if(!doc)throw Error('Document not found');parent=itemUri(doc.item_id);resourceType=url.searchParams.has('box')?'evidence':'text_page';content=lib.fetch(uri).text;const range=args.range?.match(/^lines:(\d+)-(\d+)$/);if(range){const lines=content.split('\n');content=lines.slice(Number(range[1])-1,Number(range[2])).join('\n');if(Number(range[2])<lines.length)nextRange='lines:'+(Number(range[2])+1)+'-'+Math.min(lines.length,Number(range[2])+Number(range[2])-Number(range[1])+1);}}}
   else if(url.hostname==='csl-styles'){resourceType='csl_style';const id=url.pathname.match(/^\/([^/]+)\.csl$/)?.[1];if(!styleList.some(([key])=>key===id))throw Error('Unknown CSL style');content=await globalThis.fetch(new URL('assets/csl/'+id+'.csl',document.baseURI)).then(r=>r.text());}
   else throw Error('Resource unavailable');const limit=Math.max(512,Math.min(65536,args.limit_bytes||16000)),fullBytes=new TextEncoder().encode(content).length;let truncated=fullBytes>limit;if(truncated){let bytes=0,part='';for(const c of content){const length=new TextEncoder().encode(c).length;if(bytes+length>limit)break;part+=c;bytes+=length;}content=part;nextRange=nextRange||'lines:'+(content.split('\n').length)+'-'+(content.split('\n').length+40);}entries.push({uri,resource_type:resourceType,item_uri:parent||null,content,complete:!truncated&&!nextRange,truncated,returned_bytes:new TextEncoder().encode(content).length,limit_bytes:limit,next_range:nextRange,continuation:nextRange});}
   return envelope('fetch',entries);
 }
 async function cite(args:any){const ids=new Set<string>();for(const uri of args.refs||[]){const url=new URL(uri);if(url.hostname==='items')ids.add(url.pathname.match(/^\/([^/]+)\.bib$/)?.[1]);else if(url.hostname==='texts'){const id=url.pathname.split('/')[1],doc=documents().find(d=>d.document_instance_id===id);if(!doc)throw Error('Document not found');ids.add(doc.item_id);}else throw Error('Cannot cite this resource');}const records=lib.csl().filter(c=>ids.has(c.id));if(records.length!==ids.size)throw Error('Citation item not found');const style=args.style?.match(/\/([^/]+)\.csl$/)?.[1]||'chicago';if(!styleList.some(([id])=>id===style))throw Error('Unknown CSL style');if(!renderCitation)throw Error('CSL renderer unavailable');const content=await renderCitation(records,style,args.locale||'zh-CN');return envelope('cite',[{refs:args.refs,style:'patchouli://csl-styles/'+style+'.csl',content}]);}
 return {find,fetch:fetchResources,cite,async call(name:string,args:any){try{return await ({find,fetch:fetchResources,cite}[name]?.(args)??Promise.reject(Error('Unknown tool')));}catch(e){return {operation:name,error:{code:'INVALID_ARGUMENT',message:e.message},meta:{library_revision:revision()},entries:[]};}}};
}
