/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckContainer {
        /**
          * @default true
         */
        "autoSync": boolean;
        /**
          * @default '高密度技术课件'
         */
        "deckTitle": string;
    }
    interface DeckPresenter {
        /**
          * @default 45
         */
        "targetMinutes": number;
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration": number;
        /**
          * @default ''
         */
        "headerTitle": string;
        /**
          * @default ''
         */
        "kicker": string;
        /**
          * @default 'normal'
         */
        "layout": 'hero' | 'split' | 'grid' | 'pipeline' | 'interactive' | 'normal';
        /**
          * @default ''
         */
        "notes": string;
        /**
          * @default ''
         */
        "slideId": string;
        /**
          * @default 'light'
         */
        "theme": 'light' | 'dark' | 'accent';
    }
    interface InteractiveDemo {
        /**
          * @default '可交互 LIVE'
         */
        "badgeText": string;
        /**
          * @default '交互范例'
         */
        "demoTitle": string;
        /**
          * @default ''
         */
        "description": string;
    }
    interface InteractiveStepper {
        /**
          * @default ''
         */
        "stepsData": string;
    }
    interface LayoutKpiGrid {
        /**
          * @default 3
         */
        "columns": number;
    }
    interface LayoutSplit {
        /**
          * @default '1-1'
         */
        "ratio": '1-1' | '1-2' | '2-1' | '1-3' | '3-1';
    }
    interface ParameterSlider {
        /**
          * @default '晚清学者章太炎主张以佛法之齐物以破除近代之……'
         */
        "contextText": string;
    }
    interface TokenizerPlayground {
        /**
          * @default '章太炎在《齐物论释》中对佛学与名学的综合辨析'
         */
        "initialText": string;
    }
    interface VectorInspector {
        /**
          * @default '章太炎 (晚清思想/古文经学)'
         */
        "initialConceptA": string;
        /**
          * @default '梁启超 (晚清维新/新民说)'
         */
        "initialConceptB": string;
    }
}
declare global {
    interface HTMLDeckContainerElement extends Components.DeckContainer, HTMLStencilElement {
    }
    var HTMLDeckContainerElement: {
        prototype: HTMLDeckContainerElement;
        new (): HTMLDeckContainerElement;
    };
    interface HTMLDeckPresenterElement extends Components.DeckPresenter, HTMLStencilElement {
    }
    var HTMLDeckPresenterElement: {
        prototype: HTMLDeckPresenterElement;
        new (): HTMLDeckPresenterElement;
    };
    interface HTMLDeckSlideElement extends Components.DeckSlide, HTMLStencilElement {
    }
    var HTMLDeckSlideElement: {
        prototype: HTMLDeckSlideElement;
        new (): HTMLDeckSlideElement;
    };
    interface HTMLInteractiveDemoElement extends Components.InteractiveDemo, HTMLStencilElement {
    }
    var HTMLInteractiveDemoElement: {
        prototype: HTMLInteractiveDemoElement;
        new (): HTMLInteractiveDemoElement;
    };
    interface HTMLInteractiveStepperElement extends Components.InteractiveStepper, HTMLStencilElement {
    }
    var HTMLInteractiveStepperElement: {
        prototype: HTMLInteractiveStepperElement;
        new (): HTMLInteractiveStepperElement;
    };
    interface HTMLLayoutKpiGridElement extends Components.LayoutKpiGrid, HTMLStencilElement {
    }
    var HTMLLayoutKpiGridElement: {
        prototype: HTMLLayoutKpiGridElement;
        new (): HTMLLayoutKpiGridElement;
    };
    interface HTMLLayoutSplitElement extends Components.LayoutSplit, HTMLStencilElement {
    }
    var HTMLLayoutSplitElement: {
        prototype: HTMLLayoutSplitElement;
        new (): HTMLLayoutSplitElement;
    };
    interface HTMLParameterSliderElement extends Components.ParameterSlider, HTMLStencilElement {
    }
    var HTMLParameterSliderElement: {
        prototype: HTMLParameterSliderElement;
        new (): HTMLParameterSliderElement;
    };
    interface HTMLTokenizerPlaygroundElement extends Components.TokenizerPlayground, HTMLStencilElement {
    }
    var HTMLTokenizerPlaygroundElement: {
        prototype: HTMLTokenizerPlaygroundElement;
        new (): HTMLTokenizerPlaygroundElement;
    };
    interface HTMLVectorInspectorElement extends Components.VectorInspector, HTMLStencilElement {
    }
    var HTMLVectorInspectorElement: {
        prototype: HTMLVectorInspectorElement;
        new (): HTMLVectorInspectorElement;
    };
    interface HTMLElementTagNameMap {
        "deck-container": HTMLDeckContainerElement;
        "deck-presenter": HTMLDeckPresenterElement;
        "deck-slide": HTMLDeckSlideElement;
        "interactive-demo": HTMLInteractiveDemoElement;
        "interactive-stepper": HTMLInteractiveStepperElement;
        "layout-kpi-grid": HTMLLayoutKpiGridElement;
        "layout-split": HTMLLayoutSplitElement;
        "parameter-slider": HTMLParameterSliderElement;
        "tokenizer-playground": HTMLTokenizerPlaygroundElement;
        "vector-inspector": HTMLVectorInspectorElement;
    }
}
declare namespace LocalJSX {
    interface DeckContainer {
        /**
          * @default true
         */
        "autoSync"?: boolean;
        /**
          * @default '高密度技术课件'
         */
        "deckTitle"?: string;
    }
    interface DeckPresenter {
        /**
          * @default 45
         */
        "targetMinutes"?: number;
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration"?: number;
        /**
          * @default ''
         */
        "headerTitle"?: string;
        /**
          * @default ''
         */
        "kicker"?: string;
        /**
          * @default 'normal'
         */
        "layout"?: 'hero' | 'split' | 'grid' | 'pipeline' | 'interactive' | 'normal';
        /**
          * @default ''
         */
        "notes"?: string;
        /**
          * @default ''
         */
        "slideId"?: string;
        /**
          * @default 'light'
         */
        "theme"?: 'light' | 'dark' | 'accent';
    }
    interface InteractiveDemo {
        /**
          * @default '可交互 LIVE'
         */
        "badgeText"?: string;
        /**
          * @default '交互范例'
         */
        "demoTitle"?: string;
        /**
          * @default ''
         */
        "description"?: string;
    }
    interface InteractiveStepper {
        /**
          * @default ''
         */
        "stepsData"?: string;
    }
    interface LayoutKpiGrid {
        /**
          * @default 3
         */
        "columns"?: number;
    }
    interface LayoutSplit {
        /**
          * @default '1-1'
         */
        "ratio"?: '1-1' | '1-2' | '2-1' | '1-3' | '3-1';
    }
    interface ParameterSlider {
        /**
          * @default '晚清学者章太炎主张以佛法之齐物以破除近代之……'
         */
        "contextText"?: string;
    }
    interface TokenizerPlayground {
        /**
          * @default '章太炎在《齐物论释》中对佛学与名学的综合辨析'
         */
        "initialText"?: string;
    }
    interface VectorInspector {
        /**
          * @default '章太炎 (晚清思想/古文经学)'
         */
        "initialConceptA"?: string;
        /**
          * @default '梁启超 (晚清维新/新民说)'
         */
        "initialConceptB"?: string;
    }

    interface DeckContainerAttributes {
        "deckTitle": string;
        "autoSync": boolean;
    }
    interface DeckPresenterAttributes {
        "targetMinutes": number;
    }
    interface DeckSlideAttributes {
        "slideId": string;
        "layout": 'hero' | 'split' | 'grid' | 'pipeline' | 'interactive' | 'normal';
        "theme": 'light' | 'dark' | 'accent';
        "headerTitle": string;
        "kicker": string;
        "notes": string;
        "duration": number;
    }
    interface InteractiveDemoAttributes {
        "demoTitle": string;
        "description": string;
        "badgeText": string;
    }
    interface InteractiveStepperAttributes {
        "stepsData": string;
    }
    interface LayoutKpiGridAttributes {
        "columns": number;
    }
    interface LayoutSplitAttributes {
        "ratio": '1-1' | '1-2' | '2-1' | '1-3' | '3-1';
    }
    interface ParameterSliderAttributes {
        "contextText": string;
    }
    interface TokenizerPlaygroundAttributes {
        "initialText": string;
    }
    interface VectorInspectorAttributes {
        "initialConceptA": string;
        "initialConceptB": string;
    }

    interface IntrinsicElements {
        "deck-container": Omit<DeckContainer, keyof DeckContainerAttributes> & { [K in keyof DeckContainer & keyof DeckContainerAttributes]?: DeckContainer[K] } & { [K in keyof DeckContainer & keyof DeckContainerAttributes as `attr:${K}`]?: DeckContainerAttributes[K] } & { [K in keyof DeckContainer & keyof DeckContainerAttributes as `prop:${K}`]?: DeckContainer[K] };
        "deck-presenter": Omit<DeckPresenter, keyof DeckPresenterAttributes> & { [K in keyof DeckPresenter & keyof DeckPresenterAttributes]?: DeckPresenter[K] } & { [K in keyof DeckPresenter & keyof DeckPresenterAttributes as `attr:${K}`]?: DeckPresenterAttributes[K] } & { [K in keyof DeckPresenter & keyof DeckPresenterAttributes as `prop:${K}`]?: DeckPresenter[K] };
        "deck-slide": Omit<DeckSlide, keyof DeckSlideAttributes> & { [K in keyof DeckSlide & keyof DeckSlideAttributes]?: DeckSlide[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `attr:${K}`]?: DeckSlideAttributes[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `prop:${K}`]?: DeckSlide[K] };
        "interactive-demo": Omit<InteractiveDemo, keyof InteractiveDemoAttributes> & { [K in keyof InteractiveDemo & keyof InteractiveDemoAttributes]?: InteractiveDemo[K] } & { [K in keyof InteractiveDemo & keyof InteractiveDemoAttributes as `attr:${K}`]?: InteractiveDemoAttributes[K] } & { [K in keyof InteractiveDemo & keyof InteractiveDemoAttributes as `prop:${K}`]?: InteractiveDemo[K] };
        "interactive-stepper": Omit<InteractiveStepper, keyof InteractiveStepperAttributes> & { [K in keyof InteractiveStepper & keyof InteractiveStepperAttributes]?: InteractiveStepper[K] } & { [K in keyof InteractiveStepper & keyof InteractiveStepperAttributes as `attr:${K}`]?: InteractiveStepperAttributes[K] } & { [K in keyof InteractiveStepper & keyof InteractiveStepperAttributes as `prop:${K}`]?: InteractiveStepper[K] };
        "layout-kpi-grid": Omit<LayoutKpiGrid, keyof LayoutKpiGridAttributes> & { [K in keyof LayoutKpiGrid & keyof LayoutKpiGridAttributes]?: LayoutKpiGrid[K] } & { [K in keyof LayoutKpiGrid & keyof LayoutKpiGridAttributes as `attr:${K}`]?: LayoutKpiGridAttributes[K] } & { [K in keyof LayoutKpiGrid & keyof LayoutKpiGridAttributes as `prop:${K}`]?: LayoutKpiGrid[K] };
        "layout-split": Omit<LayoutSplit, keyof LayoutSplitAttributes> & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes]?: LayoutSplit[K] } & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes as `attr:${K}`]?: LayoutSplitAttributes[K] } & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes as `prop:${K}`]?: LayoutSplit[K] };
        "parameter-slider": Omit<ParameterSlider, keyof ParameterSliderAttributes> & { [K in keyof ParameterSlider & keyof ParameterSliderAttributes]?: ParameterSlider[K] } & { [K in keyof ParameterSlider & keyof ParameterSliderAttributes as `attr:${K}`]?: ParameterSliderAttributes[K] } & { [K in keyof ParameterSlider & keyof ParameterSliderAttributes as `prop:${K}`]?: ParameterSlider[K] };
        "tokenizer-playground": Omit<TokenizerPlayground, keyof TokenizerPlaygroundAttributes> & { [K in keyof TokenizerPlayground & keyof TokenizerPlaygroundAttributes]?: TokenizerPlayground[K] } & { [K in keyof TokenizerPlayground & keyof TokenizerPlaygroundAttributes as `attr:${K}`]?: TokenizerPlaygroundAttributes[K] } & { [K in keyof TokenizerPlayground & keyof TokenizerPlaygroundAttributes as `prop:${K}`]?: TokenizerPlayground[K] };
        "vector-inspector": Omit<VectorInspector, keyof VectorInspectorAttributes> & { [K in keyof VectorInspector & keyof VectorInspectorAttributes]?: VectorInspector[K] } & { [K in keyof VectorInspector & keyof VectorInspectorAttributes as `attr:${K}`]?: VectorInspectorAttributes[K] } & { [K in keyof VectorInspector & keyof VectorInspectorAttributes as `prop:${K}`]?: VectorInspector[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deck-container": LocalJSX.IntrinsicElements["deck-container"] & JSXBase.HTMLAttributes<HTMLDeckContainerElement>;
            "deck-presenter": LocalJSX.IntrinsicElements["deck-presenter"] & JSXBase.HTMLAttributes<HTMLDeckPresenterElement>;
            "deck-slide": LocalJSX.IntrinsicElements["deck-slide"] & JSXBase.HTMLAttributes<HTMLDeckSlideElement>;
            "interactive-demo": LocalJSX.IntrinsicElements["interactive-demo"] & JSXBase.HTMLAttributes<HTMLInteractiveDemoElement>;
            "interactive-stepper": LocalJSX.IntrinsicElements["interactive-stepper"] & JSXBase.HTMLAttributes<HTMLInteractiveStepperElement>;
            "layout-kpi-grid": LocalJSX.IntrinsicElements["layout-kpi-grid"] & JSXBase.HTMLAttributes<HTMLLayoutKpiGridElement>;
            "layout-split": LocalJSX.IntrinsicElements["layout-split"] & JSXBase.HTMLAttributes<HTMLLayoutSplitElement>;
            "parameter-slider": LocalJSX.IntrinsicElements["parameter-slider"] & JSXBase.HTMLAttributes<HTMLParameterSliderElement>;
            "tokenizer-playground": LocalJSX.IntrinsicElements["tokenizer-playground"] & JSXBase.HTMLAttributes<HTMLTokenizerPlaygroundElement>;
            "vector-inspector": LocalJSX.IntrinsicElements["vector-inspector"] & JSXBase.HTMLAttributes<HTMLVectorInspectorElement>;
        }
    }
}
