import {Component,h,Prop,State,Element} from '@stencil/core';
@Component({tag:'requirements-lab',styleUrl:'requirements-lab.css',shadow:false})
export class RequirementsLab {
 @Element() el:HTMLElement;@Prop() active=false;@State() field='family';@State() values={family:'赵',given:'德宇',issued:'2001-06',pages:'12–15'};@State() edges:any[]=[];
 private observer:ResizeObserver;private scrolled=()=>this.measure();
 componentDidLoad(){this.el.addEventListener('scroll',this.scrolled,true);this.observer=new ResizeObserver(()=>this.measure());this.observer.observe(this.el);this.measure();}
 disconnectedCallback(){this.observer?.disconnect();this.el.removeEventListener('scroll',this.scrolled,true);}
 private measure(){requestAnimationFrame(()=>{const rect=this.el.querySelector('.requirements-layout')?.getBoundingClientRect();if(!rect?.width)return;const labels={family:'作者姓',given:'作者名',issued:'出版日期',pages:'页码'},edges=Object.entries(labels).flatMap(([field,label])=>{const node=this.el.querySelector('g[data-field="'+field+'"]')?.getBoundingClientRect(),input=this.el.querySelector('input[aria-label="'+label+'"]')?.getBoundingClientRect();return node&&input?[{x1:node.right-rect.left+4,y1:node.top+node.height/2-rect.top,x2:input.left-rect.left-7,y2:input.top+input.height/2-rect.top}]:[];});if(JSON.stringify(edges)!==JSON.stringify(this.edges))this.edges=edges;});}
 private pick(field:string){this.field=field;requestAnimationFrame(()=>{const input=this.el.querySelector('[data-form-field="'+field+'"] input') as HTMLInputElement;input?.focus();});}
 render(){return <section class="requirements-layout" aria-label="充分且必要的需求链"><div class="requirements-graph"><mermaid-diagram diagram="needs" selectedField={this.field} onFieldPick={event=>this.pick(event.detail)} onDiagramReady={()=>this.measure()}/></div><div class="requirements-form"><div class="requirements-form-heading"><h2>对应的表单元素</h2><p>本例需要识别人、比较出版时间与精确征引。</p></div><section class="requirements-fields" aria-label="CSL字段录入示例">{[['family','作者姓','姓 · family'],['given','作者名','名 · given'],['issued','出版日期','日期 · date-parts'],['pages','页码','页码范围 · page']].map(([key,label,caption])=><label class={this.field===key?'concept-focus':''} data-form-field={key}>{caption}<input aria-label={label} value={this.values[key]} onInput={(e:any)=>this.values={...this.values,[key]:e.target.value}}/></label>)}<p>需求改变时，字段集合也随之调整。</p></section></div><svg class="requirements-links" aria-hidden="true"><defs><marker id="needs-form-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 L10 5 L0 10 Z"/></marker></defs>{this.edges.map(edge=><path d={`M${edge.x1} ${edge.y1} C${edge.x1+28} ${edge.y1},${edge.x2-28} ${edge.y2},${edge.x2} ${edge.y2}`} marker-end="url(#needs-form-arrow)"/>)}</svg></section>;}
}
