import {Component,Fragment,h,Prop,State,Event,EventEmitter} from '@stencil/core';
import {liveLibrary} from '../../lib/live-library';
import {prepareMaterialPack,importPreparedPack,PreparedPack} from '../../lib/material-pack';
import {browserNotes,validateBrowserNotes,restoreBrowserNotes} from '../../lib/browser-notes';
import {readRuns} from '../../lib/research-records';
import {selectItem} from '../../lib/research-context';
import {downloadBytes} from '../shared/download';
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
@Component({tag:'material-package',styleUrl:'material-package.css',shadow:false})
export class MaterialPackage {
  @Prop() opened=false;@Event() packageClosed:EventEmitter<void>;
  @State() prepared:PreparedPack;@State() message='';@State() busy=false;
  private async prepare(data:Uint8Array){this.prepared=undefined;this.busy=true;try{this.prepared=await prepareMaterialPack(liveLibrary.getLibrary(),data,text=>this.message=text);this.message='校验通过。新增 '+this.prepared.records.length+' 条；已存在 '+this.prepared.skipped+' 条。确认后追加入库。';}catch(e){this.message=e.message;}finally{this.busy=false;}}
  private async commit(){if(!this.prepared||this.busy)return;this.busy=true;try{const ids=await importPreparedPack(liveLibrary.getLibrary(),this.prepared);if(ids[0])selectItem(ids[0]);this.message='已追加入库 '+ids.length+' 条；原有文献与编辑保留。';this.prepared=undefined;}catch(e){this.message=e.message;}finally{this.busy=false;}}
  private async backup(){this.busy=true;try{const lib=liveLibrary.getLibrary(),native=await lib.backup();downloadBytes(zipSync({'patchouli.zip':native,'browser-drafts.json':strToU8(JSON.stringify(browserNotes())),'reading-records.json':strToU8(JSON.stringify({schema:'pku-reading-records/v1',libraryId:lib.libraryId,runs:readRuns(lib)})),'README.txt':strToU8('Patchouli.zip 含SQLite与全部PDF。课程阅读记录保存在SQLite的x-pku-research扩展中，并在reading-records.json重复导出供核查。browser-drafts.json 含独立Markdown、卡片、聊天、词表及概念导入稿；不含API配置或密钥。概念原稿也可在概念附录另行下载。')},{level:0}),'week04-complete-backup.zip');this.message='完整备份已下载：SQLite、PDF、阅读轮次、候选、人工版本与复核。';}catch(e){this.message=e.message;}finally{this.busy=false;}}
  private async restore(file:File){if(!confirm('恢复会替换当前书库和原件。请先下载当前完整备份。确认在这份副本中恢复？'))return;this.busy=true;try{const entries=unzipSync(new Uint8Array(await file.arrayBuffer())),native=entries['patchouli.zip'];if(!native||!entries['reading-records.json'])throw Error('不是课程完整备份，请选择 week04-complete-backup.zip');const record=JSON.parse(strFromU8(entries['reading-records.json']));if(record.schema!=='pku-reading-records/v1'||!Array.isArray(record.runs))throw Error('阅读记录格式错误');let undo:()=>void;try{if(entries['browser-drafts.json'])undo=restoreBrowserNotes(validateBrowserNotes(JSON.parse(strFromU8(entries['browser-drafts.json']))));await liveLibrary.getLibrary().restore(native,true);}catch(error){undo?.();throw error;}window.dispatchEvent(new CustomEvent('week04-library-change'));window.dispatchEvent(new CustomEvent('course-reading-change'));this.message='已恢复数据库、原件与独立草稿；即将刷新并重新打开。';setTimeout(()=>location.reload(),800);}catch(e){this.message=e.message;}finally{this.busy=false;}}
  render(){return <div hidden={!this.opened} class="material-package-overlay" role="dialog" aria-modal="true" aria-label="材料包与完整备份"><section class="material-package-dialog"><header><div><h2>材料包与完整备份</h2><p>新材料先校验，再追加入库。原件和研究稿仅在本机使用。</p></div><button disabled={this.busy} onClick={()=>this.packageClosed.emit()}>关闭 ×</button></header><div class="package-actions"><label>导入新的材料包 ZIP<input aria-label="导入材料包" type="file" accept=".zip" disabled={this.busy} onChange={async(e:any)=>{const file=e.target.files?.[0];e.target.value='';if(file)await this.prepare(new Uint8Array(await file.arrayBuffer()));}}/></label></div>
    {this.prepared&&<><p>{this.prepared.manifest.title} · {this.prepared.manifest.description}</p><div class="package-preview"><table><thead><tr><th>材料</th><th>类型</th><th>实际 PDF 页数</th><th>范围提示</th></tr></thead><tbody>{this.prepared.records.map(r=><tr><td>{r.title}</td><td>{r.kind}</td><td>{r.attachments.reduce((n,a)=>n+a.pages.length,0)||'工作稿'}</td><td>{r.note||'预处理文字仍须与原页核对'}</td></tr>)}</tbody></table></div><button disabled={this.busy||!this.prepared.records.length} onClick={()=>void this.commit()}>确认追加入库</button></>}
    <hr/><div class="package-actions"><button disabled={this.busy} onClick={()=>void this.backup()}>下载完整备份（数据库＋原件＋阅读记录）</button><label>恢复完整备份<input aria-label="恢复完整备份" type="file" accept=".zip" disabled={this.busy} onChange={(e:any)=>{const file=e.target.files?.[0];e.target.value='';if(file)void this.restore(file);}}/></label></div><p role="status">{this.busy?'处理中，请保留此页。 ':''}{this.message}</p></section></div>;}
}
