import {Component,h,State} from '@stencil/core';
import {parseConceptAppendix,validateConcepts,conceptMarkdown,ConceptCategory} from '../../lib/concept-appendix';
import {downloadBytes} from '../shared/download';
const storageKey='week04-concept-appendix/v1';
@Component({tag:'glossary-view',shadow:false})
export class GlossaryView{
 @State() categories:ConceptCategory[]=[];@State() query='';@State() selected='';@State() message='';@State() regex=false;
 private defaults:ConceptCategory[]=[];
 async componentWillLoad(){this.defaults=validateConcepts(await (await fetch(new URL('assets/data/glossary.json',document.baseURI).href)).json()).categories;this.categories=this.defaults;try{const saved=localStorage.getItem(storageKey);if(saved){this.categories=validateConcepts(JSON.parse(saved)).categories;const count=this.categories.reduce((n,c)=>n+c.terms.length,0),defaultCount=this.defaults.reduce((n,c)=>n+c.terms.length,0);this.message='当前显示本地导入附录 '+count+' 条；课程附录为 '+defaultCount+' 条。可先下载当前原稿，再恢复课程附录或导入新版。';}}catch{this.message='上次导入的数据不可读取，已显示课程原稿。';}}
 private async load(file:File){try{if(file.size>1000000)throw Error('原稿超过1MB，请拆分后导入');const text=await file.text(),parsed=file.name.toLowerCase().endsWith('.json')?validateConcepts(JSON.parse(text)):parseConceptAppendix(text);localStorage.setItem(storageKey,JSON.stringify(parsed));this.categories=parsed.categories;this.query='';this.message='已导入 '+parsed.categories.reduce((n,c)=>n+c.terms.length,0)+' 条概念，刷新后仍保留；概念原稿不作为模型指令。';}catch(e){this.message='导入失败，保留原附录：'+e.message;}}
 render(){let pattern:RegExp,queryError='';try{if(this.regex&&this.query)pattern=new RegExp(this.query,'i');}catch{queryError='正则表达式格式错误';}const filter=(t:any)=>{const value=t.term+' '+(t.en||'')+' '+t.definition;return this.regex&&this.query?(pattern?pattern.test(value):false):value.toLowerCase().includes(this.query.toLowerCase());};return <div class="glossary"><aside><div class="concept-import"><label>导入本地修改原稿<input aria-label="导入概念附录" type="file" accept=".md,.txt,.json" onChange={(e:any)=>{const file=e.target.files?.[0];e.target.value='';if(file)void this.load(file);}}/></label><button onClick={()=>downloadBytes(new TextEncoder().encode(conceptMarkdown(this.categories)),'第四周概念讲解附录.md')}>下载可编辑原稿</button><button onClick={()=>{localStorage.removeItem(storageKey);this.categories=this.defaults;this.message='已恢复课程原稿。';}}>恢复课程附录</button><p role="status">{queryError||this.message||'修改原稿后直接导入；右上角可返回原页。'}</p></div><input aria-label="搜索术语" placeholder="搜索术语 / English" value={this.query} onInput={(e:any)=>this.query=e.target.value}/><label class="concept-regex"><input type="checkbox" checked={this.regex} onChange={(e:any)=>this.regex=e.target.checked}/>正则查找</label>{this.categories.flatMap(c=>c.terms.filter(filter)).map(t=><button onClick={()=>{this.selected=t.term;document.getElementById('term-'+t.term)?.scrollIntoView({block:'center'});}}>{t.term}</button>)}</aside><div class="glossary-main">{this.categories.map(c=><section><h3>{c.label}</h3>{c.terms.filter(filter).map(t=><article id={'term-'+t.term} class={{'concept-card':true,on:t.term===this.selected}}><h3>{t.term} <small>{t.en}</small></h3><p style={{whiteSpace:'pre-wrap'}}>{t.definition}</p>{t.first_slide&&<a href={'#'+t.first_slide}>课程页面 {t.first_slide} · </a>}{t.wiki?.url&&<a target="_blank" rel="noopener noreferrer" href={t.wiki.url}>参考 ↗</a>}</article>)}</section>)}</div></div>;}
}
