import {Component,h,Prop,State,Watch,Event,EventEmitter} from '@stencil/core';
import {liveLibrary} from '../../lib/live-library';
import {selectedItem} from '../../lib/research-context';
import {patchouliSession} from '../../lib/patchouli-session';
@Component({tag:'library-browser',styleUrl:'library-browser.css',shadow:false})
export class LibraryBrowser {
 @Prop() kind:'tags'|'collections'='tags';@Prop() query='';@Prop() selectedId='';@State() current='';@State() entries:any[]=[];@State() items:any[]=[];@State() editing=false;@State() name='';@State() busy=false;
 @Event() organizeFeedback:EventEmitter<string>;private off:()=>void;
 private get lib(){return liveLibrary.getLibrary();}
 componentWillLoad(){this.off=liveLibrary.subscribe(state=>{if(state==='ready')this.refresh();});this.restore();}
 disconnectedCallback(){this.off?.();}
 @Watch('kind') restore(){if(!this.lib)return;this.current=patchouliSession(this.lib.db).tools.organize?.[this.kind]||'';this.editing=false;this.refresh();}
 @Watch('query') queryChanged(){this.refresh();}
 private refresh(){const lib=this.lib;if(!lib)return;this.entries=this.kind==='tags'?lib.rows("select t.tag id,t.tag name,count(distinct t.item_id) count from item_tag_memberships t join items i on i.item_id=t.item_id where t.is_active=1 and i.deleted_at is null and i.merged_into_item_id is null group by t.tag order by t.tag"):lib.collections().map(c=>({id:c.collection_id,name:c.name,count:lib.items({collection:c.collection_id}).length}));if(this.current&&!this.entries.some(e=>e.id===this.current))this.current='';this.items=lib.items({query:this.query,...(this.kind==='tags'?{tag:this.current}:{collection:this.current})});}
 private pick(id:string){this.current=id;const session=patchouliSession(this.lib.db);(session.tools.organize ||= {})[this.kind]=id;this.refresh();}
 private async create(){if(!this.name.trim()||this.busy)return;this.busy=true;try{if(this.kind==='collections'){const id=await this.lib.createCollection(this.name);this.pick(id);}else{const id=this.selectedId||selectedItem(),record=this.lib.items().find(i=>i.item_id===id);if(!record)throw Error('请先选择题录');const names=await window.DotNet.invokeMethodAsync('CoreProbe','NormalizeTags',[...JSON.parse(record.tags_json||'[]'),this.name.trim()]);await this.lib.mutate(()=>this.lib.run('update items set tags_json=?,updated_at=? where item_id=?',[JSON.stringify(names),new Date().toISOString(),id]));this.pick(this.name.trim());}this.editing=false;this.name='';this.organizeFeedback.emit('已更新'+(this.kind==='tags'?'标签':'集合'));}catch(e){this.organizeFeedback.emit(e.message);}finally{this.busy=false;this.refresh();}}
 private async membership(){if(!this.current||!this.selectedId)return;this.busy=true;try{const record=this.lib.items().find(i=>i.item_id===this.selectedId);if(this.kind==='collections'){const included=!!this.lib.rows('select item_id from item_collections where item_id=? and collection_id=?',[this.selectedId,this.current]).length;await this.lib.setCollection(this.selectedId,this.current,!included);}else{const names=JSON.parse(record.tags_json||'[]'),next=names.includes(this.current)?names.filter(n=>n!==this.current):[...names,this.current],normalized=await window.DotNet.invokeMethodAsync('CoreProbe','NormalizeTags',next);await this.lib.mutate(()=>this.lib.run('update items set tags_json=?,updated_at=? where item_id=?',[JSON.stringify(normalized),new Date().toISOString(),this.selectedId]));}this.refresh();this.organizeFeedback.emit('已更新所选题录的'+(this.kind==='tags'?'标签':'集合'));}catch(e){this.organizeFeedback.emit(e.message);}finally{this.busy=false;}}
 render(){const label=this.kind==='tags'?'标签':'集合';return <section class="organization-library" aria-label={label+'与书库'}><aside class="organization-sidebar"><header><h3>{label}</h3><button aria-label={'新建'+label} title={'新建'+label} disabled={this.busy} onClick={()=>this.editing=!this.editing}>＋</button></header>{this.editing&&<form onSubmit={e=>{e.preventDefault();void this.create();}}><input aria-label={'新'+(this.kind==='tags'?'标签':'收藏')} placeholder={label+'名称'} value={this.name} onInput={(e:any)=>this.name=e.target.value}/><button disabled={!this.name.trim()||this.busy}>创建</button></form>}<nav role="tree" aria-label={label+'列表'}><button role="treeitem" aria-selected={String(!this.current)} class={!this.current?'is-current':''} onClick={()=>this.pick('')}><span>全部文献</span><small>{this.lib?.items().length||0}</small></button>{this.entries.map(entry=><button role="treeitem" aria-selected={String(this.current===entry.id)} class={this.current===entry.id?'is-current':''} onClick={()=>this.pick(entry.id)} title={entry.name}><span>{this.kind==='tags'?'# ':'▱ '}{entry.name}</span><small>{entry.count}</small></button>)}</nav>{this.current&&<button class="organization-membership" disabled={!this.selectedId||this.busy} onClick={()=>void this.membership()}>切换所选题录的{label}归属</button>}</aside><main class="organization-grid"><library-treegrid items={this.items} selectedId={this.selectedId}/></main></section>;}
}
