/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckContainer {
    }
    interface DeckPresenter {
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration": number;
        /**
          * @default ""
         */
        "headerTitle": string;
        /**
          * @default ""
         */
        "kicker": string;
        /**
          * @default "normal"
         */
        "layout": | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        /**
          * @default ""
         */
        "notes": string;
        /**
          * @default ""
         */
        "slideId": string;
        /**
          * @default "light"
         */
        "theme": "light" | "dark" | "accent";
    }
    interface LayoutSplit {
        /**
          * @default "1-1"
         */
        "ratio": "1-1" | "1-2" | "2-1" | "1-3" | "3-1";
    }
    interface LessonLab {
        "demoId": string;
    }
}
declare global {
    interface HTMLDeckContainerElement extends Components.DeckContainer, HTMLStencilElement {
    }
    var HTMLDeckContainerElement: {
        prototype: HTMLDeckContainerElement;
        new (): HTMLDeckContainerElement;
    };
    interface HTMLDeckPresenterElement extends Components.DeckPresenter, HTMLStencilElement {
    }
    var HTMLDeckPresenterElement: {
        prototype: HTMLDeckPresenterElement;
        new (): HTMLDeckPresenterElement;
    };
    interface HTMLDeckSlideElement extends Components.DeckSlide, HTMLStencilElement {
    }
    var HTMLDeckSlideElement: {
        prototype: HTMLDeckSlideElement;
        new (): HTMLDeckSlideElement;
    };
    interface HTMLLayoutSplitElement extends Components.LayoutSplit, HTMLStencilElement {
    }
    var HTMLLayoutSplitElement: {
        prototype: HTMLLayoutSplitElement;
        new (): HTMLLayoutSplitElement;
    };
    interface HTMLLessonLabElement extends Components.LessonLab, HTMLStencilElement {
    }
    var HTMLLessonLabElement: {
        prototype: HTMLLessonLabElement;
        new (): HTMLLessonLabElement;
    };
    interface HTMLElementTagNameMap {
        "deck-container": HTMLDeckContainerElement;
        "deck-presenter": HTMLDeckPresenterElement;
        "deck-slide": HTMLDeckSlideElement;
        "layout-split": HTMLLayoutSplitElement;
        "lesson-lab": HTMLLessonLabElement;
    }
}
declare namespace LocalJSX {
    interface DeckContainer {
    }
    interface DeckPresenter {
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration"?: number;
        /**
          * @default ""
         */
        "headerTitle"?: string;
        /**
          * @default ""
         */
        "kicker"?: string;
        /**
          * @default "normal"
         */
        "layout"?: | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        /**
          * @default ""
         */
        "notes"?: string;
        /**
          * @default ""
         */
        "slideId"?: string;
        /**
          * @default "light"
         */
        "theme"?: "light" | "dark" | "accent";
    }
    interface LayoutSplit {
        /**
          * @default "1-1"
         */
        "ratio"?: "1-1" | "1-2" | "2-1" | "1-3" | "3-1";
    }
    interface LessonLab {
        "demoId"?: string;
    }

    interface DeckSlideAttributes {
        "slideId": string;
        "layout": | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        "theme": "light" | "dark" | "accent";
        "headerTitle": string;
        "kicker": string;
        "notes": string;
        "duration": number;
    }
    interface LayoutSplitAttributes {
        "ratio": "1-1" | "1-2" | "2-1" | "1-3" | "3-1";
    }
    interface LessonLabAttributes {
        "demoId": string;
    }

    interface IntrinsicElements {
        "deck-container": DeckContainer;
        "deck-presenter": DeckPresenter;
        "deck-slide": Omit<DeckSlide, keyof DeckSlideAttributes> & { [K in keyof DeckSlide & keyof DeckSlideAttributes]?: DeckSlide[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `attr:${K}`]?: DeckSlideAttributes[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `prop:${K}`]?: DeckSlide[K] };
        "layout-split": Omit<LayoutSplit, keyof LayoutSplitAttributes> & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes]?: LayoutSplit[K] } & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes as `attr:${K}`]?: LayoutSplitAttributes[K] } & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes as `prop:${K}`]?: LayoutSplit[K] };
        "lesson-lab": Omit<LessonLab, keyof LessonLabAttributes> & { [K in keyof LessonLab & keyof LessonLabAttributes]?: LessonLab[K] } & { [K in keyof LessonLab & keyof LessonLabAttributes as `attr:${K}`]?: LessonLabAttributes[K] } & { [K in keyof LessonLab & keyof LessonLabAttributes as `prop:${K}`]?: LessonLab[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deck-container": LocalJSX.IntrinsicElements["deck-container"] & JSXBase.HTMLAttributes<HTMLDeckContainerElement>;
            "deck-presenter": LocalJSX.IntrinsicElements["deck-presenter"] & JSXBase.HTMLAttributes<HTMLDeckPresenterElement>;
            "deck-slide": LocalJSX.IntrinsicElements["deck-slide"] & JSXBase.HTMLAttributes<HTMLDeckSlideElement>;
            "layout-split": LocalJSX.IntrinsicElements["layout-split"] & JSXBase.HTMLAttributes<HTMLLayoutSplitElement>;
            "lesson-lab": LocalJSX.IntrinsicElements["lesson-lab"] & JSXBase.HTMLAttributes<HTMLLessonLabElement>;
        }
    }
}
