/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckContainer {
    }
    interface DeckPresenter {
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration": number;
        /**
          * @default ""
         */
        "headerTitle": string;
        /**
          * @default ""
         */
        "kicker": string;
        /**
          * @default "normal"
         */
        "layout": | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        /**
          * @default ""
         */
        "notes": string;
        /**
          * @default ""
         */
        "slideId": string;
        /**
          * @default "light"
         */
        "theme": "light" | "dark" | "accent";
    }
    interface LayoutSplit {
        /**
          * @default "1-1"
         */
        "ratio": "1-1" | "1-2" | "2-1" | "1-3" | "3-1";
    }
    interface LessonLab {
        "demoId": string;
    }
    interface ModelConnection {
    }
    interface ModelExperiment {
        "demoId": string;
        /**
          * @default false
         */
        "examplesOnly": boolean;
    }
    interface ProcessExplainer {
        "demoId": string;
        /**
          * @default {}
         */
        "snapshot": any;
    }
}
declare global {
    interface HTMLDeckContainerElement extends Components.DeckContainer, HTMLStencilElement {
    }
    var HTMLDeckContainerElement: {
        prototype: HTMLDeckContainerElement;
        new (): HTMLDeckContainerElement;
    };
    interface HTMLDeckPresenterElement extends Components.DeckPresenter, HTMLStencilElement {
    }
    var HTMLDeckPresenterElement: {
        prototype: HTMLDeckPresenterElement;
        new (): HTMLDeckPresenterElement;
    };
    interface HTMLDeckSlideElement extends Components.DeckSlide, HTMLStencilElement {
    }
    var HTMLDeckSlideElement: {
        prototype: HTMLDeckSlideElement;
        new (): HTMLDeckSlideElement;
    };
    interface HTMLLayoutSplitElement extends Components.LayoutSplit, HTMLStencilElement {
    }
    var HTMLLayoutSplitElement: {
        prototype: HTMLLayoutSplitElement;
        new (): HTMLLayoutSplitElement;
    };
    interface HTMLLessonLabElement extends Components.LessonLab, HTMLStencilElement {
    }
    var HTMLLessonLabElement: {
        prototype: HTMLLessonLabElement;
        new (): HTMLLessonLabElement;
    };
    interface HTMLModelConnectionElement extends Components.ModelConnection, HTMLStencilElement {
    }
    var HTMLModelConnectionElement: {
        prototype: HTMLModelConnectionElement;
        new (): HTMLModelConnectionElement;
    };
    interface HTMLModelExperimentElement extends Components.ModelExperiment, HTMLStencilElement {
    }
    var HTMLModelExperimentElement: {
        prototype: HTMLModelExperimentElement;
        new (): HTMLModelExperimentElement;
    };
    interface HTMLProcessExplainerElement extends Components.ProcessExplainer, HTMLStencilElement {
    }
    var HTMLProcessExplainerElement: {
        prototype: HTMLProcessExplainerElement;
        new (): HTMLProcessExplainerElement;
    };
    interface HTMLElementTagNameMap {
        "deck-container": HTMLDeckContainerElement;
        "deck-presenter": HTMLDeckPresenterElement;
        "deck-slide": HTMLDeckSlideElement;
        "layout-split": HTMLLayoutSplitElement;
        "lesson-lab": HTMLLessonLabElement;
        "model-connection": HTMLModelConnectionElement;
        "model-experiment": HTMLModelExperimentElement;
        "process-explainer": HTMLProcessExplainerElement;
    }
}
declare namespace LocalJSX {
    interface DeckContainer {
    }
    interface DeckPresenter {
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration"?: number;
        /**
          * @default ""
         */
        "headerTitle"?: string;
        /**
          * @default ""
         */
        "kicker"?: string;
        /**
          * @default "normal"
         */
        "layout"?: | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        /**
          * @default ""
         */
        "notes"?: string;
        /**
          * @default ""
         */
        "slideId"?: string;
        /**
          * @default "light"
         */
        "theme"?: "light" | "dark" | "accent";
    }
    interface LayoutSplit {
        /**
          * @default "1-1"
         */
        "ratio"?: "1-1" | "1-2" | "2-1" | "1-3" | "3-1";
    }
    interface LessonLab {
        "demoId"?: string;
    }
    interface ModelConnection {
    }
    interface ModelExperiment {
        "demoId"?: string;
        /**
          * @default false
         */
        "examplesOnly"?: boolean;
    }
    interface ProcessExplainer {
        "demoId"?: string;
        /**
          * @default {}
         */
        "snapshot"?: any;
    }

    interface DeckSlideAttributes {
        "slideId": string;
        "layout": | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        "theme": "light" | "dark" | "accent";
        "headerTitle": string;
        "kicker": string;
        "notes": string;
        "duration": number;
    }
    interface LayoutSplitAttributes {
        "ratio": "1-1" | "1-2" | "2-1" | "1-3" | "3-1";
    }
    interface LessonLabAttributes {
        "demoId": string;
    }
    interface ModelExperimentAttributes {
        "demoId": string;
        "examplesOnly": boolean;
    }
    interface ProcessExplainerAttributes {
        "demoId": string;
        "snapshot": string;
    }

    interface IntrinsicElements {
        "deck-container": DeckContainer;
        "deck-presenter": DeckPresenter;
        "deck-slide": Omit<DeckSlide, keyof DeckSlideAttributes> & { [K in keyof DeckSlide & keyof DeckSlideAttributes]?: DeckSlide[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `attr:${K}`]?: DeckSlideAttributes[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `prop:${K}`]?: DeckSlide[K] };
        "layout-split": Omit<LayoutSplit, keyof LayoutSplitAttributes> & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes]?: LayoutSplit[K] } & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes as `attr:${K}`]?: LayoutSplitAttributes[K] } & { [K in keyof LayoutSplit & keyof LayoutSplitAttributes as `prop:${K}`]?: LayoutSplit[K] };
        "lesson-lab": Omit<LessonLab, keyof LessonLabAttributes> & { [K in keyof LessonLab & keyof LessonLabAttributes]?: LessonLab[K] } & { [K in keyof LessonLab & keyof LessonLabAttributes as `attr:${K}`]?: LessonLabAttributes[K] } & { [K in keyof LessonLab & keyof LessonLabAttributes as `prop:${K}`]?: LessonLab[K] };
        "model-connection": ModelConnection;
        "model-experiment": Omit<ModelExperiment, keyof ModelExperimentAttributes> & { [K in keyof ModelExperiment & keyof ModelExperimentAttributes]?: ModelExperiment[K] } & { [K in keyof ModelExperiment & keyof ModelExperimentAttributes as `attr:${K}`]?: ModelExperimentAttributes[K] } & { [K in keyof ModelExperiment & keyof ModelExperimentAttributes as `prop:${K}`]?: ModelExperiment[K] };
        "process-explainer": Omit<ProcessExplainer, keyof ProcessExplainerAttributes> & { [K in keyof ProcessExplainer & keyof ProcessExplainerAttributes]?: ProcessExplainer[K] } & { [K in keyof ProcessExplainer & keyof ProcessExplainerAttributes as `attr:${K}`]?: ProcessExplainerAttributes[K] } & { [K in keyof ProcessExplainer & keyof ProcessExplainerAttributes as `prop:${K}`]?: ProcessExplainer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deck-container": LocalJSX.IntrinsicElements["deck-container"] & JSXBase.HTMLAttributes<HTMLDeckContainerElement>;
            "deck-presenter": LocalJSX.IntrinsicElements["deck-presenter"] & JSXBase.HTMLAttributes<HTMLDeckPresenterElement>;
            "deck-slide": LocalJSX.IntrinsicElements["deck-slide"] & JSXBase.HTMLAttributes<HTMLDeckSlideElement>;
            "layout-split": LocalJSX.IntrinsicElements["layout-split"] & JSXBase.HTMLAttributes<HTMLLayoutSplitElement>;
            "lesson-lab": LocalJSX.IntrinsicElements["lesson-lab"] & JSXBase.HTMLAttributes<HTMLLessonLabElement>;
            "model-connection": LocalJSX.IntrinsicElements["model-connection"] & JSXBase.HTMLAttributes<HTMLModelConnectionElement>;
            "model-experiment": LocalJSX.IntrinsicElements["model-experiment"] & JSXBase.HTMLAttributes<HTMLModelExperimentElement>;
            "process-explainer": LocalJSX.IntrinsicElements["process-explainer"] & JSXBase.HTMLAttributes<HTMLProcessExplainerElement>;
        }
    }
}
