<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PublishTrimmed>false</PublishTrimmed>
    <RuntimeFrameworkVersion>10.0.8</RuntimeFrameworkVersion>
    <TargetLatestRuntimePatch>false</TargetLatestRuntimePatch>
    <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>
  <ItemGroup>
    <KnownWebAssemblySdkPack Update="Microsoft.NET.Sdk.WebAssembly.Pack" WebAssemblySdkPackVersion="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
    <PackageReference Include="Fsharp.Citeproc" Version="1.1.0" />
    <PackageReference Include="Markdig" Version="1.3.2" />
    <Compile Include="../vendor/patchouli/src/Patchouli.Core/**/*.cs" />
    <Compile Include="../vendor/patchouli/src/Patchouli.Infrastructure/Csl/FsharpCiteprocProcessor.cs" />
    <Compile Include="../vendor/patchouli/src/Patchouli.Infrastructure/Documents/*.cs" />
  </ItemGroup>
</Project>
