import {Component,h,Prop,State,Watch,Method} from '@stencil/core';
import {liveLibrary} from '../../lib/live-library';
import {pdfWorkflow,PdfProgress} from '../../lib/pdf-workflow';
import {isOcrReady,preloadOcr} from '../../lib/ocr';
@Component({tag:'ocr-queue',styleUrl:'ocr-queue.css',shadow:false})
export class OcrQueue {
 @Prop() documentId='';@Prop() confirmToken=0;@State() confirm=false;@State() from=1;@State() to=1;@State() replace=true;@State() runs:any[]=[];@State() jobs:any[]=[];@State() progress:PdfProgress=pdfWorkflow.state;@State() error='';@State() loading=false;@State() ready=isOcrReady();
 private off:()=>void;private flowOff:()=>void;private processing=false;
 componentWillLoad(){this.off=liveLibrary.subscribe(state=>{if(state==='ready')this.refresh();});this.flowOff=pdfWorkflow.subscribe(state=>{this.progress={...state};this.ready=isOcrReady();});if(this.confirmToken)this.ask();}
 disconnectedCallback(){this.off?.();this.flowOff?.();}
 @Watch('confirmToken') requested(){if(this.confirmToken)this.ask();}
 @Method() async openConfirmation(){this.ask();}
 @Watch('documentId') documentChanged(){this.from=1;this.to=this.pages.length;}
 private get lib(){return liveLibrary.getLibrary();}private get doc(){return this.lib?.rows('select d.*,i.title from document_instances d join items i on i.item_id=d.item_id where document_instance_id=?',[this.documentId])[0];}private get pages(){return this.lib?.pages(this.documentId)||[];}
 private refresh(){this.runs=this.lib.rows('select o.*,i.title,f.file_name from ocr_runs o join document_instances d on d.document_instance_id=o.document_instance_id join file_assets f on f.file_asset_id=d.file_asset_id join items i on i.item_id=d.item_id order by o.updated_at desc limit 50');}
 private ask(){this.confirm=true;this.from=1;this.to=this.pages.length;this.error='';this.ready=isOcrReady();}
 private async load(){this.loading=true;this.error='';try{await preloadOcr();this.ready=true;}catch(e){this.error=e.message;}finally{this.loading=false;}}
 private enqueue(){if(!this.ready||!this.doc)return;if(!Number.isInteger(this.from)||!Number.isInteger(this.to)||this.from<1||this.to>this.pages.length||this.to<this.from){this.error='请填写有效的页码范围。';return;}const job={id:crypto.randomUUID(),documentId:this.documentId,title:this.doc.title,from:this.from,to:this.to,replace:this.replace,state:'queued',detail:'等待处理'};this.jobs=[...this.jobs,job];this.confirm=false;void this.process();}
 private async process(){if(this.processing)return;this.processing=true;try{while(this.jobs.some(j=>j.state==='queued')){if(pdfWorkflow.state.busy)break;const job=this.jobs.find(j=>j.state==='queued');job.state='running';this.jobs=[...this.jobs];try{await pdfWorkflow.process(job.documentId,{mode:'ocr',from:job.from,to:job.to,replace:job.replace,onProgress:progress=>{job.detail=progress.detail;this.jobs=[...this.jobs];}});job.state='completed';job.detail=pdfWorkflow.state.detail;}catch(e){job.state=pdfWorkflow.state.phase==='cancelled'?'cancelled':'failed';job.detail=pdfWorkflow.state.detail||e.message;}this.jobs=[...this.jobs];this.refresh();}}finally{this.processing=false;}}
 private stateLabel(state:string){return {queued:'排队中',running:'处理中',completed:'已完成',failed:'失败',cancelled:'已取消'}[state]||state;}
 render(){const doc=this.doc;return <section class="ocr-queue" aria-label="OCR队列页"><header class="ocr-queue-toolbar"><h3>OCR 队列</h3><button disabled={!doc||!this.pages.length} onClick={()=>this.ask()}>对当前文献进行OCR</button>{this.jobs.some(j=>j.state==='queued')&&!this.processing&&<button disabled={this.progress.busy} onClick={()=>void this.process()}>继续队列</button>}{this.progress.busy&&<button onClick={()=>pdfWorkflow.cancel()}>停止当前任务</button>}<span>{this.ready?'PP-OCRv4 已就绪':'OCR 模型待加载'}</span></header><div class="ocr-queue-table"><table><thead><tr><th>文献 / 文件</th><th>范围</th><th>状态</th><th>处理信息</th><th>操作</th></tr></thead><tbody>{this.jobs.map(job=><tr class="ocr-job" data-state={job.state}><td title={job.title}>{job.title}</td><td>{job.from}–{job.to}页</td><td>{this.stateLabel(job.state)}</td><td>{job.detail}</td><td>{job.state==='running'?<button onClick={()=>pdfWorkflow.cancel()}>停止</button>:job.state==='queued'?<button onClick={()=>this.jobs=this.jobs.map(j=>j.id===job.id?{...j,state:'cancelled',detail:'取消排队'}:j)}>移出队列</button>:<button onClick={()=>{this.jobs=this.jobs.map(j=>j.id===job.id?{...j,state:'queued',detail:'等待重试'}:j);void this.process();}}>重试</button>}</td></tr>)}{this.runs.map(run=><tr><td title={run.title}>{run.file_name||run.title}</td><td>已记录修订</td><td>{this.stateLabel(run.state)}</td><td>{run.engine_id} · {run.model_id}</td><td><button onClick={()=>window.dispatchEvent(new CustomEvent('workbench-open-document',{detail:'patchouli://texts/'+run.document_instance_id+'/page-1.md'}))}>查看原页</button></td></tr>)}</tbody></table>{!this.jobs.length&&!this.runs.length&&<p>队列为空。选择当前文献与页码范围后开始识别。</p>}</div>{this.confirm&&<div class="ocr-confirm-backdrop"><section class="ocr-confirm-dialog" role="dialog" aria-modal="true" aria-label="确认当前文献OCR"><h3>是否对当前文献进行 OCR？</h3><p>{doc?.title||'请选择文献'}</p><div class="ocr-range"><label>起始页<input aria-label="OCR起始页" type="number" min="1" max={this.pages.length} value={this.from} onInput={(e:any)=>this.from=Number(e.target.value)}/></label><label>结束页<input aria-label="OCR结束页" type="number" min="1" max={this.pages.length} value={this.to} onInput={(e:any)=>this.to=Number(e.target.value)}/></label><span>共 {this.pages.length} 页</span></div><label><input type="checkbox" checked={this.replace} onChange={(e:any)=>this.replace=e.target.checked}/>重新识别已有文字，产生新修订</label><p class="ocr-dialog-status" role="status">{this.error||(this.loading?'正在加载模型…':this.ready?'PP-OCRv4 已就绪':'先加载本机 OCR 模型即可识别。')}</p><footer><button onClick={()=>this.confirm=false}>取消</button>{!this.ready&&<button disabled={this.loading} onClick={()=>void this.load()}>加载OCR模型</button>}<button disabled={!this.ready||this.loading||!doc} onClick={()=>this.enqueue()}>确认并加入队列</button></footer></section></div>}</section>;}
}
