/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CourseApp {
    }
    interface DeckPresenter {
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration": number;
        /**
          * @default ""
         */
        "headerTitle": string;
        /**
          * @default ""
         */
        "kicker": string;
        /**
          * @default "normal"
         */
        "layout": | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        /**
          * @default ""
         */
        "notes": string;
        /**
          * @default ""
         */
        "slideId": string;
        /**
          * @default "light"
         */
        "theme": "light" | "dark" | "accent";
    }
    interface MaterialFlow {
        /**
          * @default "P03"
         */
        "pageId": string;
    }
    interface NoteFlow {
        /**
          * @default "P20"
         */
        "pageId": string;
    }
    interface ProcessWorkspace {
        /**
          * @default "P01"
         */
        "topicId": string;
    }
    interface ProjectStart {
    }
    interface ReadingFlow {
        /**
          * @default "P14"
         */
        "pageId": string;
    }
    interface SourceReader {
        /**
          * @default ""
         */
        "attachmentId": string;
        /**
          * @default 1
         */
        "page": number;
    }
    interface SystemFlow {
        /**
          * @default "P29"
         */
        "pageId": string;
    }
}
declare global {
    interface HTMLCourseAppElement extends Components.CourseApp, HTMLStencilElement {
    }
    var HTMLCourseAppElement: {
        prototype: HTMLCourseAppElement;
        new (): HTMLCourseAppElement;
    };
    interface HTMLDeckPresenterElement extends Components.DeckPresenter, HTMLStencilElement {
    }
    var HTMLDeckPresenterElement: {
        prototype: HTMLDeckPresenterElement;
        new (): HTMLDeckPresenterElement;
    };
    interface HTMLDeckSlideElement extends Components.DeckSlide, HTMLStencilElement {
    }
    var HTMLDeckSlideElement: {
        prototype: HTMLDeckSlideElement;
        new (): HTMLDeckSlideElement;
    };
    interface HTMLMaterialFlowElement extends Components.MaterialFlow, HTMLStencilElement {
    }
    var HTMLMaterialFlowElement: {
        prototype: HTMLMaterialFlowElement;
        new (): HTMLMaterialFlowElement;
    };
    interface HTMLNoteFlowElement extends Components.NoteFlow, HTMLStencilElement {
    }
    var HTMLNoteFlowElement: {
        prototype: HTMLNoteFlowElement;
        new (): HTMLNoteFlowElement;
    };
    interface HTMLProcessWorkspaceElement extends Components.ProcessWorkspace, HTMLStencilElement {
    }
    var HTMLProcessWorkspaceElement: {
        prototype: HTMLProcessWorkspaceElement;
        new (): HTMLProcessWorkspaceElement;
    };
    interface HTMLProjectStartElement extends Components.ProjectStart, HTMLStencilElement {
    }
    var HTMLProjectStartElement: {
        prototype: HTMLProjectStartElement;
        new (): HTMLProjectStartElement;
    };
    interface HTMLReadingFlowElement extends Components.ReadingFlow, HTMLStencilElement {
    }
    var HTMLReadingFlowElement: {
        prototype: HTMLReadingFlowElement;
        new (): HTMLReadingFlowElement;
    };
    interface HTMLSourceReaderElement extends Components.SourceReader, HTMLStencilElement {
    }
    var HTMLSourceReaderElement: {
        prototype: HTMLSourceReaderElement;
        new (): HTMLSourceReaderElement;
    };
    interface HTMLSystemFlowElement extends Components.SystemFlow, HTMLStencilElement {
    }
    var HTMLSystemFlowElement: {
        prototype: HTMLSystemFlowElement;
        new (): HTMLSystemFlowElement;
    };
    interface HTMLElementTagNameMap {
        "course-app": HTMLCourseAppElement;
        "deck-presenter": HTMLDeckPresenterElement;
        "deck-slide": HTMLDeckSlideElement;
        "material-flow": HTMLMaterialFlowElement;
        "note-flow": HTMLNoteFlowElement;
        "process-workspace": HTMLProcessWorkspaceElement;
        "project-start": HTMLProjectStartElement;
        "reading-flow": HTMLReadingFlowElement;
        "source-reader": HTMLSourceReaderElement;
        "system-flow": HTMLSystemFlowElement;
    }
}
declare namespace LocalJSX {
    interface CourseApp {
    }
    interface DeckPresenter {
    }
    interface DeckSlide {
        /**
          * @default 2
         */
        "duration"?: number;
        /**
          * @default ""
         */
        "headerTitle"?: string;
        /**
          * @default ""
         */
        "kicker"?: string;
        /**
          * @default "normal"
         */
        "layout"?: | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        /**
          * @default ""
         */
        "notes"?: string;
        /**
          * @default ""
         */
        "slideId"?: string;
        /**
          * @default "light"
         */
        "theme"?: "light" | "dark" | "accent";
    }
    interface MaterialFlow {
        /**
          * @default "P03"
         */
        "pageId"?: string;
    }
    interface NoteFlow {
        /**
          * @default "P20"
         */
        "pageId"?: string;
    }
    interface ProcessWorkspace {
        /**
          * @default "P01"
         */
        "topicId"?: string;
    }
    interface ProjectStart {
    }
    interface ReadingFlow {
        /**
          * @default "P14"
         */
        "pageId"?: string;
    }
    interface SourceReader {
        /**
          * @default ""
         */
        "attachmentId"?: string;
        /**
          * @default 1
         */
        "page"?: number;
    }
    interface SystemFlow {
        /**
          * @default "P29"
         */
        "pageId"?: string;
    }

    interface DeckSlideAttributes {
        "slideId": string;
        "layout": | "hero"
    | "split"
    | "grid"
    | "pipeline"
    | "interactive"
    | "normal";
        "theme": "light" | "dark" | "accent";
        "headerTitle": string;
        "kicker": string;
        "notes": string;
        "duration": number;
    }
    interface MaterialFlowAttributes {
        "pageId": string;
    }
    interface NoteFlowAttributes {
        "pageId": string;
    }
    interface ProcessWorkspaceAttributes {
        "topicId": string;
    }
    interface ReadingFlowAttributes {
        "pageId": string;
    }
    interface SourceReaderAttributes {
        "attachmentId": string;
        "page": number;
    }
    interface SystemFlowAttributes {
        "pageId": string;
    }

    interface IntrinsicElements {
        "course-app": CourseApp;
        "deck-presenter": DeckPresenter;
        "deck-slide": Omit<DeckSlide, keyof DeckSlideAttributes> & { [K in keyof DeckSlide & keyof DeckSlideAttributes]?: DeckSlide[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `attr:${K}`]?: DeckSlideAttributes[K] } & { [K in keyof DeckSlide & keyof DeckSlideAttributes as `prop:${K}`]?: DeckSlide[K] };
        "material-flow": Omit<MaterialFlow, keyof MaterialFlowAttributes> & { [K in keyof MaterialFlow & keyof MaterialFlowAttributes]?: MaterialFlow[K] } & { [K in keyof MaterialFlow & keyof MaterialFlowAttributes as `attr:${K}`]?: MaterialFlowAttributes[K] } & { [K in keyof MaterialFlow & keyof MaterialFlowAttributes as `prop:${K}`]?: MaterialFlow[K] };
        "note-flow": Omit<NoteFlow, keyof NoteFlowAttributes> & { [K in keyof NoteFlow & keyof NoteFlowAttributes]?: NoteFlow[K] } & { [K in keyof NoteFlow & keyof NoteFlowAttributes as `attr:${K}`]?: NoteFlowAttributes[K] } & { [K in keyof NoteFlow & keyof NoteFlowAttributes as `prop:${K}`]?: NoteFlow[K] };
        "process-workspace": Omit<ProcessWorkspace, keyof ProcessWorkspaceAttributes> & { [K in keyof ProcessWorkspace & keyof ProcessWorkspaceAttributes]?: ProcessWorkspace[K] } & { [K in keyof ProcessWorkspace & keyof ProcessWorkspaceAttributes as `attr:${K}`]?: ProcessWorkspaceAttributes[K] } & { [K in keyof ProcessWorkspace & keyof ProcessWorkspaceAttributes as `prop:${K}`]?: ProcessWorkspace[K] };
        "project-start": ProjectStart;
        "reading-flow": Omit<ReadingFlow, keyof ReadingFlowAttributes> & { [K in keyof ReadingFlow & keyof ReadingFlowAttributes]?: ReadingFlow[K] } & { [K in keyof ReadingFlow & keyof ReadingFlowAttributes as `attr:${K}`]?: ReadingFlowAttributes[K] } & { [K in keyof ReadingFlow & keyof ReadingFlowAttributes as `prop:${K}`]?: ReadingFlow[K] };
        "source-reader": Omit<SourceReader, keyof SourceReaderAttributes> & { [K in keyof SourceReader & keyof SourceReaderAttributes]?: SourceReader[K] } & { [K in keyof SourceReader & keyof SourceReaderAttributes as `attr:${K}`]?: SourceReaderAttributes[K] } & { [K in keyof SourceReader & keyof SourceReaderAttributes as `prop:${K}`]?: SourceReader[K] };
        "system-flow": Omit<SystemFlow, keyof SystemFlowAttributes> & { [K in keyof SystemFlow & keyof SystemFlowAttributes]?: SystemFlow[K] } & { [K in keyof SystemFlow & keyof SystemFlowAttributes as `attr:${K}`]?: SystemFlowAttributes[K] } & { [K in keyof SystemFlow & keyof SystemFlowAttributes as `prop:${K}`]?: SystemFlow[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "course-app": LocalJSX.IntrinsicElements["course-app"] & JSXBase.HTMLAttributes<HTMLCourseAppElement>;
            "deck-presenter": LocalJSX.IntrinsicElements["deck-presenter"] & JSXBase.HTMLAttributes<HTMLDeckPresenterElement>;
            "deck-slide": LocalJSX.IntrinsicElements["deck-slide"] & JSXBase.HTMLAttributes<HTMLDeckSlideElement>;
            "material-flow": LocalJSX.IntrinsicElements["material-flow"] & JSXBase.HTMLAttributes<HTMLMaterialFlowElement>;
            "note-flow": LocalJSX.IntrinsicElements["note-flow"] & JSXBase.HTMLAttributes<HTMLNoteFlowElement>;
            "process-workspace": LocalJSX.IntrinsicElements["process-workspace"] & JSXBase.HTMLAttributes<HTMLProcessWorkspaceElement>;
            "project-start": LocalJSX.IntrinsicElements["project-start"] & JSXBase.HTMLAttributes<HTMLProjectStartElement>;
            "reading-flow": LocalJSX.IntrinsicElements["reading-flow"] & JSXBase.HTMLAttributes<HTMLReadingFlowElement>;
            "source-reader": LocalJSX.IntrinsicElements["source-reader"] & JSXBase.HTMLAttributes<HTMLSourceReaderElement>;
            "system-flow": LocalJSX.IntrinsicElements["system-flow"] & JSXBase.HTMLAttributes<HTMLSystemFlowElement>;
        }
    }
}
