import {MARKDOWN_DIAGRAMS} from '../../lib/markdown-diagrams';
import {Component,h,Prop,State,Element,Watch,Method} from '@stencil/core';
import {MARKDOWN_TEMPLATES} from '../../lib/markdown-templates';
import {liveLibrary} from '../../lib/live-library';
import {selectedItem} from '../../lib/research-context';
import {downloadBytes} from '../shared/download';
import {PatchouliRequest} from '../../lib/patchouli-pages';
@Component({tag:'markdown-lab',styleUrl:'markdown-lab.css',shadow:false})
export class MarkdownLab {
 @Element() el:HTMLElement;@Prop() pageId='D20';@Prop() showDiagram=true;@Prop() active=false;
 @State() mode='edit';@State() selectedIndex=0;@State() selectedSection='';@State() editing=false;@State() text='';@State() ready=false;@State() message='';@State() reader:PatchouliRequest;
 private tools:any;private editor:any;private template='';private started=false;private off:()=>void;
 private get key(){return 'week04-markdown-'+this.pageId;}
 private get config(){return MARKDOWN_TEMPLATES[this.pageId]||MARKDOWN_TEMPLATES.D20;}
 componentDidLoad(){this.off=liveLibrary.subscribe(state=>{if(state==='ready'&&this.active)void this.init();});if(this.active)void this.init();}
 disconnectedCallback(){this.off?.();this.editor?.destroy();}
 @Watch('active') activate(){if(this.active)void this.init();}
 private async init(){if(this.started){requestAnimationFrame(()=>this.mount());return;}if(!liveLibrary.getLibrary())return;this.started=true;try{const url=new URL('assets/skos/tools.mjs',document.baseURI).href;this.tools=await import(/* webpackIgnore: true */url);const lib=liveLibrary.getLibrary(),item=lib.items().find(i=>i.item_id===selectedItem())||lib.items()[0];const source=lib.rows("select s.*,p.page_index from search_units s join pages p on p.page_id=s.page_id join document_instances d on d.document_instance_id=s.document_instance_id where d.item_id=? and s.status='current' and trim(s.resolved_text)<>'' order by p.page_index,s.ordinal limit 1",[item?.item_id])[0];const hit=source?{uri:'patchouli://texts/'+source.document_instance_id+'/page-'+(source.page_index+1)+'.md?rev='+source.tree_revision_id+'&box='+source.box_id}:null;this.template=this.config.text.replaceAll('{{title}}',item?.title||'填写所用文献').replaceAll('{{uri}}',hit?.uri||'patchouli://texts/文档ID/page-1.md?rev=修订ID&box=文本块ID');this.text=localStorage.getItem(this.key)??this.template;this.ready=true;requestAnimationFrame(()=>this.mount());}catch(e){this.message=e.message;this.started=false;}}
 private change=(text:string)=>{this.text=text;localStorage.setItem(this.key,text);this.message='草稿已保存在本机';};
 componentDidRender(){if(this.active){this.mount();this.highlightPreview();}}
 private mount(){if(!this.tools||!this.ready)return;const host=this.el.querySelector('.markdown-code');if(host&&!host.querySelector('.cm-editor')){this.editor?.destroy();this.editor=this.tools.createEditor(host,this.text,this.change,'markdown');if(this.selectedSection)this.editor.highlightSection(this.selectedSection);}}
 @Method() async getText(){return this.text;}
 @Method() async setText(text:string){this.change(text);this.editor?.setText(text);}
 private citation=(event:MouseEvent)=>{const anchor=(event.target as HTMLElement).closest('a');if(!anchor)return;const uri=anchor.getAttribute('href')||'';if(!uri.startsWith('patchouli:'))return;event.preventDefault();try{const url=new URL(uri),match=url.pathname.match(/^\/([^/]+)\/page-(\d+)\.md$/);const evidence=liveLibrary.getLibrary().fetch(uri);if(url.hostname!=='texts'||!match||!evidence.text)throw Error('请填写可以解析的原文证据 URI');this.reader={page:'reader',documentId:match[1],pageNumber:Number(match[2]),revisionId:url.searchParams.get('rev')||'',evidenceUri:uri};this.editor?.destroy();this.editor=null;}catch(e){this.message=e.message;}};
 private content(){if(this.reader)return <patchouli-app active={this.active} initialPage="reader" request={this.reader} externalReturn={true} returnLabel="返回Markdown笔记" onPatchouliEditChange={event=>this.editing=event.detail} onPatchouliReturn={()=>{this.reader=null;requestAnimationFrame(()=>this.mount());}}/>;
 return <section class="markdown-lab" aria-label={this.config.title+'Markdown练习'}><header class="example-toolbar"><strong>{this.config.title}</strong><nav aria-label="Markdown模式"><button class={this.mode==='edit'?'selected':''} aria-pressed={String(this.mode==='edit')} onClick={()=>this.mode='edit'}>书写</button><button class={this.mode==='preview'?'selected':''} aria-pressed={String(this.mode==='preview')} onClick={()=>this.mode='preview'}>预览</button></nav><span role="status">{this.message||'自由填写 · Markdown'}</span><button onClick={()=>{this.change(this.template);this.editor?.setText(this.template);}}>恢复模板</button><button onClick={()=>downloadBytes(new TextEncoder().encode(this.text),this.config.title+'.md','text/markdown')}>下载 .md</button></header><p class="markdown-prompt">{this.config.hint}</p><div class="markdown-code" hidden={this.mode!=='edit'}/>{this.mode==='preview'&&this.tools&&<article class="markdown-preview" onClick={this.citation} innerHTML={this.tools.renderMarkdown(this.text)}/>}</section>;
 }
 private pick(index:number){const node=MARKDOWN_DIAGRAMS[this.pageId]?.nodes[index];if(!node||this.editing)return;this.selectedIndex=index;this.selectedSection=node.section;if(this.reader){this.reader=null;requestAnimationFrame(()=>{this.mount();this.editor?.highlightSection(this.selectedSection);});}else if(this.mode==='edit')this.editor?.highlightSection(node.section);else requestAnimationFrame(()=>this.highlightPreview());}
 private highlightPreview(){const preview=this.el.querySelector('.markdown-preview');if(!preview)return;preview.querySelectorAll('.markdown-glow').forEach(el=>el.classList.remove('markdown-glow'));const heading=[...preview.querySelectorAll('h1,h2,h3')].find(el=>el.textContent.trim()===this.selectedSection);if(!heading)return;heading.classList.add('markdown-glow');let next=heading.nextElementSibling;while(next&&!/^H[123]$/.test(next.tagName)){next.classList.add('markdown-glow');next=next.nextElementSibling;}if(this.selectedSection)(heading as HTMLElement).scrollIntoView({block:'nearest'});}
 render(){if(!this.showDiagram)return <div class="markdown-workspace">{this.content()}</div>;return <div class="markdown-example-layout"><div class="markdown-workspace">{this.content()}</div><concept-map pageId={this.pageId} config={MARKDOWN_DIAGRAMS[this.pageId]} selectedIndex={this.selectedIndex} disabled={this.editing} hint="点击图中节点，定位模板段落" onDiagramPick={event=>this.pick(event.detail)}/></div>;}

}
